/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKNI_710AE_DISCOVERY_DRV_H
#define _MOCKNI_710AE_DISCOVERY_DRV_H

#include "unity.h"
#include "ni_710ae_discovery_drv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockni_710ae_discovery_drv_Init(void);
void Mockni_710ae_discovery_drv_Destroy(void);
void Mockni_710ae_discovery_drv_Verify(void);




#define ni710ae_discovery_IgnoreAndReturn(cmock_retval) ni710ae_discovery_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ni710ae_discovery_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define ni710ae_discovery_StopIgnore() ni710ae_discovery_CMockStopIgnore()
void ni710ae_discovery_CMockStopIgnore(void);
#define ni710ae_discovery_ExpectAnyArgsAndReturn(cmock_retval) ni710ae_discovery_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void ni710ae_discovery_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define ni710ae_discovery_ExpectAndReturn(cfg_node, periphbase_addr, memory_pool, memory_index, max_node_count, cmock_retval) ni710ae_discovery_CMockExpectAndReturn(__LINE__, cfg_node, periphbase_addr, memory_pool, memory_index, max_node_count, cmock_retval)
void ni710ae_discovery_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* cfg_node, const uintptr_t periphbase_addr, struct ni710ae_discovery_tree_t* memory_pool, uint16_t* memory_index, uint16_t max_node_count, int cmock_to_return);
typedef int (* CMOCK_ni710ae_discovery_CALLBACK)(struct ni710ae_discovery_tree_t* cfg_node, const uintptr_t periphbase_addr, struct ni710ae_discovery_tree_t* memory_pool, uint16_t* memory_index, uint16_t max_node_count, int cmock_num_calls);
void ni710ae_discovery_AddCallback(CMOCK_ni710ae_discovery_CALLBACK Callback);
void ni710ae_discovery_Stub(CMOCK_ni710ae_discovery_CALLBACK Callback);
#define ni710ae_discovery_StubWithCallback ni710ae_discovery_Stub
#define ni710ae_discovery_ExpectWithArrayAndReturn(cfg_node, cfg_node_Depth, periphbase_addr, memory_pool, memory_pool_Depth, memory_index, memory_index_Depth, max_node_count, cmock_retval) ni710ae_discovery_CMockExpectWithArrayAndReturn(__LINE__, cfg_node, cfg_node_Depth, periphbase_addr, memory_pool, memory_pool_Depth, memory_index, memory_index_Depth, max_node_count, cmock_retval)
void ni710ae_discovery_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* cfg_node, int cfg_node_Depth, const uintptr_t periphbase_addr, struct ni710ae_discovery_tree_t* memory_pool, int memory_pool_Depth, uint16_t* memory_index, int memory_index_Depth, uint16_t max_node_count, int cmock_to_return);
#define ni710ae_discovery_ReturnThruPtr_cfg_node(cfg_node) ni710ae_discovery_CMockReturnMemThruPtr_cfg_node(__LINE__, cfg_node, sizeof(struct ni710ae_discovery_tree_t))
#define ni710ae_discovery_ReturnArrayThruPtr_cfg_node(cfg_node, cmock_len) ni710ae_discovery_CMockReturnMemThruPtr_cfg_node(__LINE__, cfg_node, cmock_len * sizeof(*cfg_node))
#define ni710ae_discovery_ReturnMemThruPtr_cfg_node(cfg_node, cmock_size) ni710ae_discovery_CMockReturnMemThruPtr_cfg_node(__LINE__, cfg_node, cmock_size)
void ni710ae_discovery_CMockReturnMemThruPtr_cfg_node(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* cfg_node, size_t cmock_size);
#define ni710ae_discovery_ReturnThruPtr_memory_pool(memory_pool) ni710ae_discovery_CMockReturnMemThruPtr_memory_pool(__LINE__, memory_pool, sizeof(struct ni710ae_discovery_tree_t))
#define ni710ae_discovery_ReturnArrayThruPtr_memory_pool(memory_pool, cmock_len) ni710ae_discovery_CMockReturnMemThruPtr_memory_pool(__LINE__, memory_pool, cmock_len * sizeof(*memory_pool))
#define ni710ae_discovery_ReturnMemThruPtr_memory_pool(memory_pool, cmock_size) ni710ae_discovery_CMockReturnMemThruPtr_memory_pool(__LINE__, memory_pool, cmock_size)
void ni710ae_discovery_CMockReturnMemThruPtr_memory_pool(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* memory_pool, size_t cmock_size);
#define ni710ae_discovery_ReturnThruPtr_memory_index(memory_index) ni710ae_discovery_CMockReturnMemThruPtr_memory_index(__LINE__, memory_index, sizeof(uint16_t))
#define ni710ae_discovery_ReturnArrayThruPtr_memory_index(memory_index, cmock_len) ni710ae_discovery_CMockReturnMemThruPtr_memory_index(__LINE__, memory_index, cmock_len * sizeof(*memory_index))
#define ni710ae_discovery_ReturnMemThruPtr_memory_index(memory_index, cmock_size) ni710ae_discovery_CMockReturnMemThruPtr_memory_index(__LINE__, memory_index, cmock_size)
void ni710ae_discovery_CMockReturnMemThruPtr_memory_index(UNITY_LINE_TYPE cmock_line, uint16_t* memory_index, size_t cmock_size);
#define ni710ae_discovery_IgnoreArg_cfg_node() ni710ae_discovery_CMockIgnoreArg_cfg_node(__LINE__)
void ni710ae_discovery_CMockIgnoreArg_cfg_node(UNITY_LINE_TYPE cmock_line);
#define ni710ae_discovery_IgnoreArg_periphbase_addr() ni710ae_discovery_CMockIgnoreArg_periphbase_addr(__LINE__)
void ni710ae_discovery_CMockIgnoreArg_periphbase_addr(UNITY_LINE_TYPE cmock_line);
#define ni710ae_discovery_IgnoreArg_memory_pool() ni710ae_discovery_CMockIgnoreArg_memory_pool(__LINE__)
void ni710ae_discovery_CMockIgnoreArg_memory_pool(UNITY_LINE_TYPE cmock_line);
#define ni710ae_discovery_IgnoreArg_memory_index() ni710ae_discovery_CMockIgnoreArg_memory_index(__LINE__)
void ni710ae_discovery_CMockIgnoreArg_memory_index(UNITY_LINE_TYPE cmock_line);
#define ni710ae_discovery_IgnoreArg_max_node_count() ni710ae_discovery_CMockIgnoreArg_max_node_count(__LINE__)
void ni710ae_discovery_CMockIgnoreArg_max_node_count(UNITY_LINE_TYPE cmock_line);
#define ni710ae_fetch_offset_address_IgnoreAndReturn(cmock_retval) ni710ae_fetch_offset_address_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ni710ae_fetch_offset_address_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t cmock_to_return);
#define ni710ae_fetch_offset_address_StopIgnore() ni710ae_fetch_offset_address_CMockStopIgnore()
void ni710ae_fetch_offset_address_CMockStopIgnore(void);
#define ni710ae_fetch_offset_address_ExpectAnyArgsAndReturn(cmock_retval) ni710ae_fetch_offset_address_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void ni710ae_fetch_offset_address_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t cmock_to_return);
#define ni710ae_fetch_offset_address_ExpectAndReturn(root, component_type, component_id, sub_feature_type, cmock_retval) ni710ae_fetch_offset_address_CMockExpectAndReturn(__LINE__, root, component_type, component_id, sub_feature_type, cmock_retval)
void ni710ae_fetch_offset_address_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* root, uint16_t component_type, uint16_t component_id, uint16_t sub_feature_type, uintptr_t cmock_to_return);
typedef uintptr_t (* CMOCK_ni710ae_fetch_offset_address_CALLBACK)(struct ni710ae_discovery_tree_t* root, uint16_t component_type, uint16_t component_id, uint16_t sub_feature_type, int cmock_num_calls);
void ni710ae_fetch_offset_address_AddCallback(CMOCK_ni710ae_fetch_offset_address_CALLBACK Callback);
void ni710ae_fetch_offset_address_Stub(CMOCK_ni710ae_fetch_offset_address_CALLBACK Callback);
#define ni710ae_fetch_offset_address_StubWithCallback ni710ae_fetch_offset_address_Stub
#define ni710ae_fetch_offset_address_ExpectWithArrayAndReturn(root, root_Depth, component_type, component_id, sub_feature_type, cmock_retval) ni710ae_fetch_offset_address_CMockExpectWithArrayAndReturn(__LINE__, root, root_Depth, component_type, component_id, sub_feature_type, cmock_retval)
void ni710ae_fetch_offset_address_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* root, int root_Depth, uint16_t component_type, uint16_t component_id, uint16_t sub_feature_type, uintptr_t cmock_to_return);
#define ni710ae_fetch_offset_address_ReturnThruPtr_root(root) ni710ae_fetch_offset_address_CMockReturnMemThruPtr_root(__LINE__, root, sizeof(struct ni710ae_discovery_tree_t))
#define ni710ae_fetch_offset_address_ReturnArrayThruPtr_root(root, cmock_len) ni710ae_fetch_offset_address_CMockReturnMemThruPtr_root(__LINE__, root, cmock_len * sizeof(*root))
#define ni710ae_fetch_offset_address_ReturnMemThruPtr_root(root, cmock_size) ni710ae_fetch_offset_address_CMockReturnMemThruPtr_root(__LINE__, root, cmock_size)
void ni710ae_fetch_offset_address_CMockReturnMemThruPtr_root(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* root, size_t cmock_size);
#define ni710ae_fetch_offset_address_IgnoreArg_root() ni710ae_fetch_offset_address_CMockIgnoreArg_root(__LINE__)
void ni710ae_fetch_offset_address_CMockIgnoreArg_root(UNITY_LINE_TYPE cmock_line);
#define ni710ae_fetch_offset_address_IgnoreArg_component_type() ni710ae_fetch_offset_address_CMockIgnoreArg_component_type(__LINE__)
void ni710ae_fetch_offset_address_CMockIgnoreArg_component_type(UNITY_LINE_TYPE cmock_line);
#define ni710ae_fetch_offset_address_IgnoreArg_component_id() ni710ae_fetch_offset_address_CMockIgnoreArg_component_id(__LINE__)
void ni710ae_fetch_offset_address_CMockIgnoreArg_component_id(UNITY_LINE_TYPE cmock_line);
#define ni710ae_fetch_offset_address_IgnoreArg_sub_feature_type() ni710ae_fetch_offset_address_CMockIgnoreArg_sub_feature_type(__LINE__)
void ni710ae_fetch_offset_address_CMockIgnoreArg_sub_feature_type(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
