/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKNI_710AE_LIB_H
#define _MOCKNI_710AE_LIB_H

#include "unity.h"
#include "ni_710ae_lib.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockni_710ae_lib_Init(void);
void Mockni_710ae_lib_Destroy(void);
void Mockni_710ae_lib_Verify(void);




#define program_ni_710ae_apu_IgnoreAndReturn(cmock_retval) program_ni_710ae_apu_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void program_ni_710ae_apu_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define program_ni_710ae_apu_StopIgnore() program_ni_710ae_apu_CMockStopIgnore()
void program_ni_710ae_apu_CMockStopIgnore(void);
#define program_ni_710ae_apu_ExpectAnyArgsAndReturn(cmock_retval) program_ni_710ae_apu_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void program_ni_710ae_apu_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define program_ni_710ae_apu_ExpectAndReturn(config, apu_config_count, dev_periphbase_addr, discovery_tree, cmock_retval) program_ni_710ae_apu_CMockExpectAndReturn(__LINE__, config, apu_config_count, dev_periphbase_addr, discovery_tree, cmock_retval)
void program_ni_710ae_apu_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct ni_710ae_component_apu_config* config, uint16_t apu_config_count, uintptr_t dev_periphbase_addr, struct ni710ae_discovery_tree_t* discovery_tree, int cmock_to_return);
typedef int (* CMOCK_program_ni_710ae_apu_CALLBACK)(const struct ni_710ae_component_apu_config* config, uint16_t apu_config_count, uintptr_t dev_periphbase_addr, struct ni710ae_discovery_tree_t* discovery_tree, int cmock_num_calls);
void program_ni_710ae_apu_AddCallback(CMOCK_program_ni_710ae_apu_CALLBACK Callback);
void program_ni_710ae_apu_Stub(CMOCK_program_ni_710ae_apu_CALLBACK Callback);
#define program_ni_710ae_apu_StubWithCallback program_ni_710ae_apu_Stub
#define program_ni_710ae_apu_ExpectWithArrayAndReturn(config, config_Depth, apu_config_count, dev_periphbase_addr, discovery_tree, discovery_tree_Depth, cmock_retval) program_ni_710ae_apu_CMockExpectWithArrayAndReturn(__LINE__, config, config_Depth, apu_config_count, dev_periphbase_addr, discovery_tree, discovery_tree_Depth, cmock_retval)
void program_ni_710ae_apu_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const struct ni_710ae_component_apu_config* config, int config_Depth, uint16_t apu_config_count, uintptr_t dev_periphbase_addr, struct ni710ae_discovery_tree_t* discovery_tree, int discovery_tree_Depth, int cmock_to_return);
#define program_ni_710ae_apu_ReturnThruPtr_discovery_tree(discovery_tree) program_ni_710ae_apu_CMockReturnMemThruPtr_discovery_tree(__LINE__, discovery_tree, sizeof(struct ni710ae_discovery_tree_t))
#define program_ni_710ae_apu_ReturnArrayThruPtr_discovery_tree(discovery_tree, cmock_len) program_ni_710ae_apu_CMockReturnMemThruPtr_discovery_tree(__LINE__, discovery_tree, cmock_len * sizeof(*discovery_tree))
#define program_ni_710ae_apu_ReturnMemThruPtr_discovery_tree(discovery_tree, cmock_size) program_ni_710ae_apu_CMockReturnMemThruPtr_discovery_tree(__LINE__, discovery_tree, cmock_size)
void program_ni_710ae_apu_CMockReturnMemThruPtr_discovery_tree(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* discovery_tree, size_t cmock_size);
#define program_ni_710ae_apu_IgnoreArg_config() program_ni_710ae_apu_CMockIgnoreArg_config(__LINE__)
void program_ni_710ae_apu_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line);
#define program_ni_710ae_apu_IgnoreArg_apu_config_count() program_ni_710ae_apu_CMockIgnoreArg_apu_config_count(__LINE__)
void program_ni_710ae_apu_CMockIgnoreArg_apu_config_count(UNITY_LINE_TYPE cmock_line);
#define program_ni_710ae_apu_IgnoreArg_dev_periphbase_addr() program_ni_710ae_apu_CMockIgnoreArg_dev_periphbase_addr(__LINE__)
void program_ni_710ae_apu_CMockIgnoreArg_dev_periphbase_addr(UNITY_LINE_TYPE cmock_line);
#define program_ni_710ae_apu_IgnoreArg_discovery_tree() program_ni_710ae_apu_CMockIgnoreArg_discovery_tree(__LINE__)
void program_ni_710ae_apu_CMockIgnoreArg_discovery_tree(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
