/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockni_710ae_discovery_drv.h"

static const char* CMockString_cfg_node = "cfg_node";
static const char* CMockString_component_id = "component_id";
static const char* CMockString_component_type = "component_type";
static const char* CMockString_max_node_count = "max_node_count";
static const char* CMockString_memory_index = "memory_index";
static const char* CMockString_memory_pool = "memory_pool";
static const char* CMockString_ni710ae_discovery = "ni710ae_discovery";
static const char* CMockString_ni710ae_fetch_offset_address = "ni710ae_fetch_offset_address";
static const char* CMockString_periphbase_addr = "periphbase_addr";
static const char* CMockString_root = "root";
static const char* CMockString_sub_feature_type = "sub_feature_type";

typedef struct _CMOCK_ni710ae_discovery_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  struct ni710ae_discovery_tree_t* Expected_cfg_node;
  uintptr_t Expected_periphbase_addr;
  struct ni710ae_discovery_tree_t* Expected_memory_pool;
  uint16_t* Expected_memory_index;
  uint16_t Expected_max_node_count;
  int Expected_cfg_node_Depth;
  int Expected_memory_pool_Depth;
  int Expected_memory_index_Depth;
  char ReturnThruPtr_cfg_node_Used;
  struct ni710ae_discovery_tree_t* ReturnThruPtr_cfg_node_Val;
  size_t ReturnThruPtr_cfg_node_Size;
  char ReturnThruPtr_memory_pool_Used;
  struct ni710ae_discovery_tree_t* ReturnThruPtr_memory_pool_Val;
  size_t ReturnThruPtr_memory_pool_Size;
  char ReturnThruPtr_memory_index_Used;
  uint16_t* ReturnThruPtr_memory_index_Val;
  size_t ReturnThruPtr_memory_index_Size;
  char IgnoreArg_cfg_node;
  char IgnoreArg_periphbase_addr;
  char IgnoreArg_memory_pool;
  char IgnoreArg_memory_index;
  char IgnoreArg_max_node_count;

} CMOCK_ni710ae_discovery_CALL_INSTANCE;

typedef struct _CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uintptr_t ReturnVal;
  struct ni710ae_discovery_tree_t* Expected_root;
  uint16_t Expected_component_type;
  uint16_t Expected_component_id;
  uint16_t Expected_sub_feature_type;
  int Expected_root_Depth;
  char ReturnThruPtr_root_Used;
  struct ni710ae_discovery_tree_t* ReturnThruPtr_root_Val;
  size_t ReturnThruPtr_root_Size;
  char IgnoreArg_root;
  char IgnoreArg_component_type;
  char IgnoreArg_component_id;
  char IgnoreArg_sub_feature_type;

} CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE;

static struct Mockni_710ae_discovery_drvInstance
{
  char ni710ae_discovery_IgnoreBool;
  int ni710ae_discovery_FinalReturn;
  char ni710ae_discovery_CallbackBool;
  CMOCK_ni710ae_discovery_CALLBACK ni710ae_discovery_CallbackFunctionPointer;
  int ni710ae_discovery_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ni710ae_discovery_CallInstance;
  char ni710ae_fetch_offset_address_IgnoreBool;
  uintptr_t ni710ae_fetch_offset_address_FinalReturn;
  char ni710ae_fetch_offset_address_CallbackBool;
  CMOCK_ni710ae_fetch_offset_address_CALLBACK ni710ae_fetch_offset_address_CallbackFunctionPointer;
  int ni710ae_fetch_offset_address_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ni710ae_fetch_offset_address_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockni_710ae_discovery_drv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.ni710ae_discovery_CallInstance;
  if (Mock.ni710ae_discovery_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ni710ae_discovery);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ni710ae_discovery_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.ni710ae_fetch_offset_address_CallInstance;
  if (Mock.ni710ae_fetch_offset_address_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ni710ae_fetch_offset_address);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ni710ae_fetch_offset_address_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockni_710ae_discovery_drv_Init(void)
{
  Mockni_710ae_discovery_drv_Destroy();
}

void Mockni_710ae_discovery_drv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int ni710ae_discovery(struct ni710ae_discovery_tree_t* cfg_node, const uintptr_t periphbase_addr, struct ni710ae_discovery_tree_t* memory_pool, uint16_t* memory_index, uint16_t max_node_count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ni710ae_discovery);
  cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ni710ae_discovery_CallInstance);
  Mock.ni710ae_discovery_CallInstance = CMock_Guts_MemNext(Mock.ni710ae_discovery_CallInstance);
  if (Mock.ni710ae_discovery_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ni710ae_discovery_FinalReturn;
    Mock.ni710ae_discovery_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ni710ae_discovery_CallbackBool &&
      Mock.ni710ae_discovery_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.ni710ae_discovery_CallbackFunctionPointer(cfg_node, periphbase_addr, memory_pool, memory_index, max_node_count, Mock.ni710ae_discovery_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_cfg_node)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_discovery,CMockString_cfg_node);
    if (cmock_call_instance->Expected_cfg_node == NULL)
      { UNITY_TEST_ASSERT_NULL(cfg_node, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cfg_node), (void*)(cfg_node), sizeof(struct ni710ae_discovery_tree_t), cmock_call_instance->Expected_cfg_node_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_periphbase_addr)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_discovery,CMockString_periphbase_addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_periphbase_addr), (void*)(&periphbase_addr), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_memory_pool)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_discovery,CMockString_memory_pool);
    if (cmock_call_instance->Expected_memory_pool == NULL)
      { UNITY_TEST_ASSERT_NULL(memory_pool, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_memory_pool), (void*)(memory_pool), sizeof(struct ni710ae_discovery_tree_t), cmock_call_instance->Expected_memory_pool_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_memory_index)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_discovery,CMockString_memory_index);
    if (cmock_call_instance->Expected_memory_index == NULL)
      { UNITY_TEST_ASSERT_NULL(memory_index, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_memory_index, memory_index, cmock_call_instance->Expected_memory_index_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_max_node_count)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_discovery,CMockString_max_node_count);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_max_node_count, max_node_count, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.ni710ae_discovery_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ni710ae_discovery_CallbackFunctionPointer(cfg_node, periphbase_addr, memory_pool, memory_index, max_node_count, Mock.ni710ae_discovery_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_cfg_node_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(cfg_node, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)cfg_node, (void*)cmock_call_instance->ReturnThruPtr_cfg_node_Val,
      cmock_call_instance->ReturnThruPtr_cfg_node_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_memory_pool_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(memory_pool, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)memory_pool, (void*)cmock_call_instance->ReturnThruPtr_memory_pool_Val,
      cmock_call_instance->ReturnThruPtr_memory_pool_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_memory_index_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(memory_index, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)memory_index, (void*)cmock_call_instance->ReturnThruPtr_memory_index_Val,
      cmock_call_instance->ReturnThruPtr_memory_index_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ni710ae_discovery(CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance, struct ni710ae_discovery_tree_t* cfg_node, int cfg_node_Depth, const uintptr_t periphbase_addr, struct ni710ae_discovery_tree_t* memory_pool, int memory_pool_Depth, uint16_t* memory_index, int memory_index_Depth, uint16_t max_node_count);
void CMockExpectParameters_ni710ae_discovery(CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance, struct ni710ae_discovery_tree_t* cfg_node, int cfg_node_Depth, const uintptr_t periphbase_addr, struct ni710ae_discovery_tree_t* memory_pool, int memory_pool_Depth, uint16_t* memory_index, int memory_index_Depth, uint16_t max_node_count)
{
  cmock_call_instance->Expected_cfg_node = cfg_node;
  cmock_call_instance->Expected_cfg_node_Depth = cfg_node_Depth;
  cmock_call_instance->IgnoreArg_cfg_node = 0;
  cmock_call_instance->ReturnThruPtr_cfg_node_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_periphbase_addr), (void*)(&periphbase_addr),
         sizeof(uintptr_t[sizeof(periphbase_addr) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_periphbase_addr = 0;
  cmock_call_instance->Expected_memory_pool = memory_pool;
  cmock_call_instance->Expected_memory_pool_Depth = memory_pool_Depth;
  cmock_call_instance->IgnoreArg_memory_pool = 0;
  cmock_call_instance->ReturnThruPtr_memory_pool_Used = 0;
  cmock_call_instance->Expected_memory_index = memory_index;
  cmock_call_instance->Expected_memory_index_Depth = memory_index_Depth;
  cmock_call_instance->IgnoreArg_memory_index = 0;
  cmock_call_instance->ReturnThruPtr_memory_index_Used = 0;
  cmock_call_instance->Expected_max_node_count = max_node_count;
  cmock_call_instance->IgnoreArg_max_node_count = 0;
}

void ni710ae_discovery_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ni710ae_discovery_CALL_INSTANCE));
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ni710ae_discovery_CallInstance = CMock_Guts_MemChain(Mock.ni710ae_discovery_CallInstance, cmock_guts_index);
  Mock.ni710ae_discovery_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ni710ae_discovery_IgnoreBool = (char)1;
}

void ni710ae_discovery_CMockStopIgnore(void)
{
  if(Mock.ni710ae_discovery_IgnoreBool)
    Mock.ni710ae_discovery_CallInstance = CMock_Guts_MemNext(Mock.ni710ae_discovery_CallInstance);
  Mock.ni710ae_discovery_IgnoreBool = (char)0;
}

void ni710ae_discovery_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ni710ae_discovery_CALL_INSTANCE));
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ni710ae_discovery_CallInstance = CMock_Guts_MemChain(Mock.ni710ae_discovery_CallInstance, cmock_guts_index);
  Mock.ni710ae_discovery_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void ni710ae_discovery_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* cfg_node, const uintptr_t periphbase_addr, struct ni710ae_discovery_tree_t* memory_pool, uint16_t* memory_index, uint16_t max_node_count, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ni710ae_discovery_CALL_INSTANCE));
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ni710ae_discovery_CallInstance = CMock_Guts_MemChain(Mock.ni710ae_discovery_CallInstance, cmock_guts_index);
  Mock.ni710ae_discovery_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ni710ae_discovery(cmock_call_instance, cfg_node, 1, periphbase_addr, memory_pool, 1, memory_index, 1, max_node_count);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ni710ae_discovery_AddCallback(CMOCK_ni710ae_discovery_CALLBACK Callback)
{
  Mock.ni710ae_discovery_IgnoreBool = (char)0;
  Mock.ni710ae_discovery_CallbackBool = (char)1;
  Mock.ni710ae_discovery_CallbackFunctionPointer = Callback;
}

void ni710ae_discovery_Stub(CMOCK_ni710ae_discovery_CALLBACK Callback)
{
  Mock.ni710ae_discovery_IgnoreBool = (char)0;
  Mock.ni710ae_discovery_CallbackBool = (char)0;
  Mock.ni710ae_discovery_CallbackFunctionPointer = Callback;
}

void ni710ae_discovery_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* cfg_node, int cfg_node_Depth, const uintptr_t periphbase_addr, struct ni710ae_discovery_tree_t* memory_pool, int memory_pool_Depth, uint16_t* memory_index, int memory_index_Depth, uint16_t max_node_count, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ni710ae_discovery_CALL_INSTANCE));
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ni710ae_discovery_CallInstance = CMock_Guts_MemChain(Mock.ni710ae_discovery_CallInstance, cmock_guts_index);
  Mock.ni710ae_discovery_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ni710ae_discovery(cmock_call_instance, cfg_node, cfg_node_Depth, periphbase_addr, memory_pool, memory_pool_Depth, memory_index, memory_index_Depth, max_node_count);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ni710ae_discovery_CMockReturnMemThruPtr_cfg_node(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* cfg_node, size_t cmock_size)
{
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_discovery_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_cfg_node_Used = 1;
  cmock_call_instance->ReturnThruPtr_cfg_node_Val = cfg_node;
  cmock_call_instance->ReturnThruPtr_cfg_node_Size = cmock_size;
}

void ni710ae_discovery_CMockReturnMemThruPtr_memory_pool(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* memory_pool, size_t cmock_size)
{
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_discovery_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_memory_pool_Used = 1;
  cmock_call_instance->ReturnThruPtr_memory_pool_Val = memory_pool;
  cmock_call_instance->ReturnThruPtr_memory_pool_Size = cmock_size;
}

void ni710ae_discovery_CMockReturnMemThruPtr_memory_index(UNITY_LINE_TYPE cmock_line, uint16_t* memory_index, size_t cmock_size)
{
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_discovery_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_memory_index_Used = 1;
  cmock_call_instance->ReturnThruPtr_memory_index_Val = memory_index;
  cmock_call_instance->ReturnThruPtr_memory_index_Size = cmock_size;
}

void ni710ae_discovery_CMockIgnoreArg_cfg_node(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_discovery_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cfg_node = 1;
}

void ni710ae_discovery_CMockIgnoreArg_periphbase_addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_discovery_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_periphbase_addr = 1;
}

void ni710ae_discovery_CMockIgnoreArg_memory_pool(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_discovery_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_memory_pool = 1;
}

void ni710ae_discovery_CMockIgnoreArg_memory_index(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_discovery_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_memory_index = 1;
}

void ni710ae_discovery_CMockIgnoreArg_max_node_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_discovery_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_discovery_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_discovery_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_max_node_count = 1;
}

uintptr_t ni710ae_fetch_offset_address(struct ni710ae_discovery_tree_t* root, uint16_t component_type, uint16_t component_id, uint16_t sub_feature_type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ni710ae_fetch_offset_address);
  cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ni710ae_fetch_offset_address_CallInstance);
  Mock.ni710ae_fetch_offset_address_CallInstance = CMock_Guts_MemNext(Mock.ni710ae_fetch_offset_address_CallInstance);
  if (Mock.ni710ae_fetch_offset_address_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ni710ae_fetch_offset_address_FinalReturn;
    memcpy((void*)(&Mock.ni710ae_fetch_offset_address_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(uintptr_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ni710ae_fetch_offset_address_CallbackBool &&
      Mock.ni710ae_fetch_offset_address_CallbackFunctionPointer != NULL)
  {
    uintptr_t cmock_cb_ret = Mock.ni710ae_fetch_offset_address_CallbackFunctionPointer(root, component_type, component_id, sub_feature_type, Mock.ni710ae_fetch_offset_address_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_root)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_fetch_offset_address,CMockString_root);
    if (cmock_call_instance->Expected_root == NULL)
      { UNITY_TEST_ASSERT_NULL(root, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_root), (void*)(root), sizeof(struct ni710ae_discovery_tree_t), cmock_call_instance->Expected_root_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_component_type)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_fetch_offset_address,CMockString_component_type);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_component_type, component_type, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_component_id)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_fetch_offset_address,CMockString_component_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_component_id, component_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_sub_feature_type)
  {
    UNITY_SET_DETAILS(CMockString_ni710ae_fetch_offset_address,CMockString_sub_feature_type);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_sub_feature_type, sub_feature_type, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.ni710ae_fetch_offset_address_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ni710ae_fetch_offset_address_CallbackFunctionPointer(root, component_type, component_id, sub_feature_type, Mock.ni710ae_fetch_offset_address_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_root_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(root, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)root, (void*)cmock_call_instance->ReturnThruPtr_root_Val,
      cmock_call_instance->ReturnThruPtr_root_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ni710ae_fetch_offset_address(CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance, struct ni710ae_discovery_tree_t* root, int root_Depth, uint16_t component_type, uint16_t component_id, uint16_t sub_feature_type);
void CMockExpectParameters_ni710ae_fetch_offset_address(CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance, struct ni710ae_discovery_tree_t* root, int root_Depth, uint16_t component_type, uint16_t component_id, uint16_t sub_feature_type)
{
  cmock_call_instance->Expected_root = root;
  cmock_call_instance->Expected_root_Depth = root_Depth;
  cmock_call_instance->IgnoreArg_root = 0;
  cmock_call_instance->ReturnThruPtr_root_Used = 0;
  cmock_call_instance->Expected_component_type = component_type;
  cmock_call_instance->IgnoreArg_component_type = 0;
  cmock_call_instance->Expected_component_id = component_id;
  cmock_call_instance->IgnoreArg_component_id = 0;
  cmock_call_instance->Expected_sub_feature_type = sub_feature_type;
  cmock_call_instance->IgnoreArg_sub_feature_type = 0;
}

void ni710ae_fetch_offset_address_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE));
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ni710ae_fetch_offset_address_CallInstance = CMock_Guts_MemChain(Mock.ni710ae_fetch_offset_address_CallInstance, cmock_guts_index);
  Mock.ni710ae_fetch_offset_address_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ni710ae_fetch_offset_address_IgnoreBool = (char)1;
}

void ni710ae_fetch_offset_address_CMockStopIgnore(void)
{
  if(Mock.ni710ae_fetch_offset_address_IgnoreBool)
    Mock.ni710ae_fetch_offset_address_CallInstance = CMock_Guts_MemNext(Mock.ni710ae_fetch_offset_address_CallInstance);
  Mock.ni710ae_fetch_offset_address_IgnoreBool = (char)0;
}

void ni710ae_fetch_offset_address_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE));
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ni710ae_fetch_offset_address_CallInstance = CMock_Guts_MemChain(Mock.ni710ae_fetch_offset_address_CallInstance, cmock_guts_index);
  Mock.ni710ae_fetch_offset_address_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void ni710ae_fetch_offset_address_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* root, uint16_t component_type, uint16_t component_id, uint16_t sub_feature_type, uintptr_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE));
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ni710ae_fetch_offset_address_CallInstance = CMock_Guts_MemChain(Mock.ni710ae_fetch_offset_address_CallInstance, cmock_guts_index);
  Mock.ni710ae_fetch_offset_address_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ni710ae_fetch_offset_address(cmock_call_instance, root, 1, component_type, component_id, sub_feature_type);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(uintptr_t[sizeof(cmock_to_return) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
}

void ni710ae_fetch_offset_address_AddCallback(CMOCK_ni710ae_fetch_offset_address_CALLBACK Callback)
{
  Mock.ni710ae_fetch_offset_address_IgnoreBool = (char)0;
  Mock.ni710ae_fetch_offset_address_CallbackBool = (char)1;
  Mock.ni710ae_fetch_offset_address_CallbackFunctionPointer = Callback;
}

void ni710ae_fetch_offset_address_Stub(CMOCK_ni710ae_fetch_offset_address_CALLBACK Callback)
{
  Mock.ni710ae_fetch_offset_address_IgnoreBool = (char)0;
  Mock.ni710ae_fetch_offset_address_CallbackBool = (char)0;
  Mock.ni710ae_fetch_offset_address_CallbackFunctionPointer = Callback;
}

void ni710ae_fetch_offset_address_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* root, int root_Depth, uint16_t component_type, uint16_t component_id, uint16_t sub_feature_type, uintptr_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE));
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ni710ae_fetch_offset_address_CallInstance = CMock_Guts_MemChain(Mock.ni710ae_fetch_offset_address_CallInstance, cmock_guts_index);
  Mock.ni710ae_fetch_offset_address_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ni710ae_fetch_offset_address(cmock_call_instance, root, root_Depth, component_type, component_id, sub_feature_type);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ni710ae_fetch_offset_address_CMockReturnMemThruPtr_root(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* root, size_t cmock_size)
{
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_fetch_offset_address_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_root_Used = 1;
  cmock_call_instance->ReturnThruPtr_root_Val = root;
  cmock_call_instance->ReturnThruPtr_root_Size = cmock_size;
}

void ni710ae_fetch_offset_address_CMockIgnoreArg_root(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_fetch_offset_address_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_root = 1;
}

void ni710ae_fetch_offset_address_CMockIgnoreArg_component_type(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_fetch_offset_address_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_component_type = 1;
}

void ni710ae_fetch_offset_address_CMockIgnoreArg_component_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_fetch_offset_address_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_component_id = 1;
}

void ni710ae_fetch_offset_address_CMockIgnoreArg_sub_feature_type(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE* cmock_call_instance = (CMOCK_ni710ae_fetch_offset_address_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ni710ae_fetch_offset_address_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sub_feature_type = 1;
}

