/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockni_710ae_lib.h"

static const char* CMockString_apu_config_count = "apu_config_count";
static const char* CMockString_config = "config";
static const char* CMockString_dev_periphbase_addr = "dev_periphbase_addr";
static const char* CMockString_discovery_tree = "discovery_tree";
static const char* CMockString_program_ni_710ae_apu = "program_ni_710ae_apu";

typedef struct _CMOCK_program_ni_710ae_apu_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct ni_710ae_component_apu_config* Expected_config;
  uint16_t Expected_apu_config_count;
  uintptr_t Expected_dev_periphbase_addr;
  struct ni710ae_discovery_tree_t* Expected_discovery_tree;
  int Expected_config_Depth;
  int Expected_discovery_tree_Depth;
  char ReturnThruPtr_discovery_tree_Used;
  struct ni710ae_discovery_tree_t* ReturnThruPtr_discovery_tree_Val;
  size_t ReturnThruPtr_discovery_tree_Size;
  char IgnoreArg_config;
  char IgnoreArg_apu_config_count;
  char IgnoreArg_dev_periphbase_addr;
  char IgnoreArg_discovery_tree;

} CMOCK_program_ni_710ae_apu_CALL_INSTANCE;

static struct Mockni_710ae_libInstance
{
  char program_ni_710ae_apu_IgnoreBool;
  int program_ni_710ae_apu_FinalReturn;
  char program_ni_710ae_apu_CallbackBool;
  CMOCK_program_ni_710ae_apu_CALLBACK program_ni_710ae_apu_CallbackFunctionPointer;
  int program_ni_710ae_apu_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE program_ni_710ae_apu_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockni_710ae_lib_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.program_ni_710ae_apu_CallInstance;
  if (Mock.program_ni_710ae_apu_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_program_ni_710ae_apu);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.program_ni_710ae_apu_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockni_710ae_lib_Init(void)
{
  Mockni_710ae_lib_Destroy();
}

void Mockni_710ae_lib_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int program_ni_710ae_apu(const struct ni_710ae_component_apu_config* config, uint16_t apu_config_count, uintptr_t dev_periphbase_addr, struct ni710ae_discovery_tree_t* discovery_tree)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_program_ni_710ae_apu);
  cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.program_ni_710ae_apu_CallInstance);
  Mock.program_ni_710ae_apu_CallInstance = CMock_Guts_MemNext(Mock.program_ni_710ae_apu_CallInstance);
  if (Mock.program_ni_710ae_apu_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.program_ni_710ae_apu_FinalReturn;
    Mock.program_ni_710ae_apu_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.program_ni_710ae_apu_CallbackBool &&
      Mock.program_ni_710ae_apu_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.program_ni_710ae_apu_CallbackFunctionPointer(config, apu_config_count, dev_periphbase_addr, discovery_tree, Mock.program_ni_710ae_apu_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_config)
  {
    UNITY_SET_DETAILS(CMockString_program_ni_710ae_apu,CMockString_config);
    if (cmock_call_instance->Expected_config == NULL)
      { UNITY_TEST_ASSERT_NULL(config, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_config), (void*)(config), sizeof(const struct ni_710ae_component_apu_config), cmock_call_instance->Expected_config_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_apu_config_count)
  {
    UNITY_SET_DETAILS(CMockString_program_ni_710ae_apu,CMockString_apu_config_count);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_apu_config_count, apu_config_count, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dev_periphbase_addr)
  {
    UNITY_SET_DETAILS(CMockString_program_ni_710ae_apu,CMockString_dev_periphbase_addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev_periphbase_addr), (void*)(&dev_periphbase_addr), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_discovery_tree)
  {
    UNITY_SET_DETAILS(CMockString_program_ni_710ae_apu,CMockString_discovery_tree);
    if (cmock_call_instance->Expected_discovery_tree == NULL)
      { UNITY_TEST_ASSERT_NULL(discovery_tree, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_discovery_tree), (void*)(discovery_tree), sizeof(struct ni710ae_discovery_tree_t), cmock_call_instance->Expected_discovery_tree_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.program_ni_710ae_apu_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.program_ni_710ae_apu_CallbackFunctionPointer(config, apu_config_count, dev_periphbase_addr, discovery_tree, Mock.program_ni_710ae_apu_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_discovery_tree_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(discovery_tree, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)discovery_tree, (void*)cmock_call_instance->ReturnThruPtr_discovery_tree_Val,
      cmock_call_instance->ReturnThruPtr_discovery_tree_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_program_ni_710ae_apu(CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance, const struct ni_710ae_component_apu_config* config, int config_Depth, uint16_t apu_config_count, uintptr_t dev_periphbase_addr, struct ni710ae_discovery_tree_t* discovery_tree, int discovery_tree_Depth);
void CMockExpectParameters_program_ni_710ae_apu(CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance, const struct ni_710ae_component_apu_config* config, int config_Depth, uint16_t apu_config_count, uintptr_t dev_periphbase_addr, struct ni710ae_discovery_tree_t* discovery_tree, int discovery_tree_Depth)
{
  cmock_call_instance->Expected_config = config;
  cmock_call_instance->Expected_config_Depth = config_Depth;
  cmock_call_instance->IgnoreArg_config = 0;
  cmock_call_instance->Expected_apu_config_count = apu_config_count;
  cmock_call_instance->IgnoreArg_apu_config_count = 0;
  memcpy((void*)(&cmock_call_instance->Expected_dev_periphbase_addr), (void*)(&dev_periphbase_addr),
         sizeof(uintptr_t[sizeof(dev_periphbase_addr) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_dev_periphbase_addr = 0;
  cmock_call_instance->Expected_discovery_tree = discovery_tree;
  cmock_call_instance->Expected_discovery_tree_Depth = discovery_tree_Depth;
  cmock_call_instance->IgnoreArg_discovery_tree = 0;
  cmock_call_instance->ReturnThruPtr_discovery_tree_Used = 0;
}

void program_ni_710ae_apu_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_program_ni_710ae_apu_CALL_INSTANCE));
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.program_ni_710ae_apu_CallInstance = CMock_Guts_MemChain(Mock.program_ni_710ae_apu_CallInstance, cmock_guts_index);
  Mock.program_ni_710ae_apu_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.program_ni_710ae_apu_IgnoreBool = (char)1;
}

void program_ni_710ae_apu_CMockStopIgnore(void)
{
  if(Mock.program_ni_710ae_apu_IgnoreBool)
    Mock.program_ni_710ae_apu_CallInstance = CMock_Guts_MemNext(Mock.program_ni_710ae_apu_CallInstance);
  Mock.program_ni_710ae_apu_IgnoreBool = (char)0;
}

void program_ni_710ae_apu_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_program_ni_710ae_apu_CALL_INSTANCE));
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.program_ni_710ae_apu_CallInstance = CMock_Guts_MemChain(Mock.program_ni_710ae_apu_CallInstance, cmock_guts_index);
  Mock.program_ni_710ae_apu_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void program_ni_710ae_apu_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct ni_710ae_component_apu_config* config, uint16_t apu_config_count, uintptr_t dev_periphbase_addr, struct ni710ae_discovery_tree_t* discovery_tree, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_program_ni_710ae_apu_CALL_INSTANCE));
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.program_ni_710ae_apu_CallInstance = CMock_Guts_MemChain(Mock.program_ni_710ae_apu_CallInstance, cmock_guts_index);
  Mock.program_ni_710ae_apu_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_program_ni_710ae_apu(cmock_call_instance, config, 1, apu_config_count, dev_periphbase_addr, discovery_tree, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void program_ni_710ae_apu_AddCallback(CMOCK_program_ni_710ae_apu_CALLBACK Callback)
{
  Mock.program_ni_710ae_apu_IgnoreBool = (char)0;
  Mock.program_ni_710ae_apu_CallbackBool = (char)1;
  Mock.program_ni_710ae_apu_CallbackFunctionPointer = Callback;
}

void program_ni_710ae_apu_Stub(CMOCK_program_ni_710ae_apu_CALLBACK Callback)
{
  Mock.program_ni_710ae_apu_IgnoreBool = (char)0;
  Mock.program_ni_710ae_apu_CallbackBool = (char)0;
  Mock.program_ni_710ae_apu_CallbackFunctionPointer = Callback;
}

void program_ni_710ae_apu_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const struct ni_710ae_component_apu_config* config, int config_Depth, uint16_t apu_config_count, uintptr_t dev_periphbase_addr, struct ni710ae_discovery_tree_t* discovery_tree, int discovery_tree_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_program_ni_710ae_apu_CALL_INSTANCE));
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.program_ni_710ae_apu_CallInstance = CMock_Guts_MemChain(Mock.program_ni_710ae_apu_CallInstance, cmock_guts_index);
  Mock.program_ni_710ae_apu_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_program_ni_710ae_apu(cmock_call_instance, config, config_Depth, apu_config_count, dev_periphbase_addr, discovery_tree, discovery_tree_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void program_ni_710ae_apu_CMockReturnMemThruPtr_discovery_tree(UNITY_LINE_TYPE cmock_line, struct ni710ae_discovery_tree_t* discovery_tree, size_t cmock_size)
{
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.program_ni_710ae_apu_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_discovery_tree_Used = 1;
  cmock_call_instance->ReturnThruPtr_discovery_tree_Val = discovery_tree;
  cmock_call_instance->ReturnThruPtr_discovery_tree_Size = cmock_size;
}

void program_ni_710ae_apu_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.program_ni_710ae_apu_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_config = 1;
}

void program_ni_710ae_apu_CMockIgnoreArg_apu_config_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.program_ni_710ae_apu_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_apu_config_count = 1;
}

void program_ni_710ae_apu_CMockIgnoreArg_dev_periphbase_addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.program_ni_710ae_apu_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev_periphbase_addr = 1;
}

void program_ni_710ae_apu_CMockIgnoreArg_discovery_tree(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_program_ni_710ae_apu_CALL_INSTANCE* cmock_call_instance = (CMOCK_program_ni_710ae_apu_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.program_ni_710ae_apu_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_discovery_tree = 1;
}

