/*
 * Arm SCP/MCP Software
 * Copyright (c) 2025, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SI0_MMAP_H
#define SI0_MMAP_H

#include <fwk_macros.h>

#define SI0_SRAM_BASE    0x120000000
#define SI0_ITC_RAM_SIZE (256 * 1024)
#define SI0_DTC_RAM_SIZE (256 * 1024)
#define SI0_ITC_RAM_BASE SI0_SRAM_BASE
#define SI0_DTC_RAM_BASE (SI0_SRAM_BASE + SI0_ITC_RAM_SIZE)

#define SI0_GIC_BASE  0x30000000
#define SI0_GIC_SIZE  (1 * FWK_MIB)
#define SI0_GICD_BASE 0x30000000
#define SI0_GICR_BASE 0x30040000

#define SI0_PERIPHERAL_BASE 0x2A000000
#define SI0_PERIPHERAL_SIZE (16 * FWK_MIB)
#define SI0_UART_BASE       0x2A400000

#define SI0_MHU_BASE                0x38000000
#define SI0_MHU_SIZE                (16 * FWK_MIB)
#define SI0_RSE2SI0_MHUV3_RCV_BASE  0x38140000
#define SI0_SI02RSE_MHUV3_SEND_BASE 0x38100000

#define SI0_ATW_BASE 0x80000000
#define SI0_ATW_SIZE (2 * FWK_GIB)

#define SI0_ATW0_CMN_BASE SI0_ATW_BASE
#define SI0_ATW0_CMN_SIZE (1 * FWK_GIB)

#define SI0_ATW1_CLUSTER_UTILITY_BASE (SI0_ATW0_CMN_BASE + SI0_ATW0_CMN_SIZE)
#define SI0_ATW1_CLUSTER_UTILITY_SIZE (256 * FWK_MIB)

#define SI0_ATW2_SMD_EXPANSION_BASE \
    (SI0_ATW1_CLUSTER_UTILITY_BASE + SI0_ATW1_CLUSTER_UTILITY_SIZE)
#define SI0_ATW2_SMD_EXPANSION_SIZE (128 * FWK_KIB)

#define SI0_ATW3_SYSTOP_PIK_BASE \
    (SI0_ATW2_SMD_EXPANSION_BASE + SI0_ATW2_SMD_EXPANSION_SIZE)
#define SI0_ATW3_SYSTOP_PIK_SIZE (64 * FWK_KIB)

#define SI0_ATW4_SYSTEM_ID_BASE \
    (SI0_ATW3_SYSTOP_PIK_BASE + SI0_ATW3_SYSTOP_PIK_SIZE)
#define SI0_ATW4_SYSTEM_ID_SIZE (64 * FWK_KIB)

#define SI0_ATW5_CSS_COUNTERS_TIMERS_BASE \
    (SI0_ATW4_SYSTEM_ID_BASE + SI0_ATW4_SYSTEM_ID_SIZE)
#define SI0_ATW5_CSS_COUNTERS_TIMERS_SIZE (192 * FWK_KIB)

#define SI0_SID_BASE (SI0_ATW4_SYSTEM_ID_BASE)

#define SI0_SMD_EXPANSION3_BASE (SI0_ATW2_SMD_EXPANSION_BASE)

#define SI0_CMN_BASE (SI0_ATW0_CMN_BASE)

#define SI0_SYSTOP_PPU_OFFSET 0x1000
#define SI0_PPU_SYS0_BASE     (SI0_ATW3_SYSTOP_PIK_BASE + SI0_SYSTOP_PPU_OFFSET)

#define SI0_REFCLK_CNTCONTROL_BASE (SI0_ATW5_CSS_COUNTERS_TIMERS_BASE)
#define SI0_REFCLK_CNTCONTROL_SIZE (64 * FWK_KIB)

#define SI0_REFCLK_CNT_BASE \
    (SI0_REFCLK_CNTCONTROL_BASE + SI0_REFCLK_CNTCONTROL_SIZE)
#define SI0_REFCLK_CNT_SIZE (64 * FWK_KIB)

#define SI0_REFCLK_CNTCTL_BASE (SI0_REFCLK_CNT_BASE + SI0_REFCLK_CNT_SIZE)
#define SI0_REFCLK_CNTCTL_SIZE (64 * FWK_KIB)

/*
 * Size of SCP's view of per-cluster utility memory region.
 */
#define SI0_CLUSTER_UTILITY_SIZE (0x4000000UL)

/*
 * Offsets of various blocks within cluster utility that is
 * mapped into SI0's address translation window 0. These offsets are applicable
 * to each cluster in the system.
 */
#define SI0_CLUSTER_UTILITY_CLUSTER_PPU_OFFSET (0x1030000UL)
#define SI0_CLUSTER_UTILITY_CLUSTER_AE_OFFSET  (0x1050000UL)
#define SI0_CLUSTER_UTILITY_CORE_PPU0_OFFSET   (0x1080000UL)
#define SI0_CLUSTER_UTILITY_CORE_PPU_OFFSET    (0x100000UL)

#endif /* SI0_MMAP_H */
