/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMOD_ATU_MMIO_EXTRA_H
#define _MOCKMOD_ATU_MMIO_EXTRA_H

#include "unity.h"
#include "mod_atu_mmio_extra.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmod_atu_mmio_extra_Init(void);
void Mockmod_atu_mmio_extra_Destroy(void);
void Mockmod_atu_mmio_extra_Verify(void);




#define mock_atu_add_region_IgnoreAndReturn(cmock_retval) mock_atu_add_region_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void mock_atu_add_region_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define mock_atu_add_region_StopIgnore() mock_atu_add_region_CMockStopIgnore()
void mock_atu_add_region_CMockStopIgnore(void);
#define mock_atu_add_region_ExpectAnyArgsAndReturn(cmock_retval) mock_atu_add_region_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void mock_atu_add_region_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define mock_atu_add_region_ExpectAndReturn(region, atu_device_id, region_idx, cmock_retval) mock_atu_add_region_CMockExpectAndReturn(__LINE__, region, atu_device_id, region_idx, cmock_retval)
void mock_atu_add_region_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct atu_region_map* region, fwk_id_t atu_device_id, uint8_t* region_idx, int cmock_to_return);
typedef int (* CMOCK_mock_atu_add_region_CALLBACK)(const struct atu_region_map* region, fwk_id_t atu_device_id, uint8_t* region_idx, int cmock_num_calls);
void mock_atu_add_region_AddCallback(CMOCK_mock_atu_add_region_CALLBACK Callback);
void mock_atu_add_region_Stub(CMOCK_mock_atu_add_region_CALLBACK Callback);
#define mock_atu_add_region_StubWithCallback mock_atu_add_region_Stub
#define mock_atu_add_region_ExpectWithArrayAndReturn(region, region_Depth, atu_device_id, region_idx, region_idx_Depth, cmock_retval) mock_atu_add_region_CMockExpectWithArrayAndReturn(__LINE__, region, region_Depth, atu_device_id, region_idx, region_idx_Depth, cmock_retval)
void mock_atu_add_region_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const struct atu_region_map* region, int region_Depth, fwk_id_t atu_device_id, uint8_t* region_idx, int region_idx_Depth, int cmock_to_return);
#define mock_atu_add_region_ReturnThruPtr_region_idx(region_idx) mock_atu_add_region_CMockReturnMemThruPtr_region_idx(__LINE__, region_idx, sizeof(uint8_t))
#define mock_atu_add_region_ReturnArrayThruPtr_region_idx(region_idx, cmock_len) mock_atu_add_region_CMockReturnMemThruPtr_region_idx(__LINE__, region_idx, cmock_len * sizeof(*region_idx))
#define mock_atu_add_region_ReturnMemThruPtr_region_idx(region_idx, cmock_size) mock_atu_add_region_CMockReturnMemThruPtr_region_idx(__LINE__, region_idx, cmock_size)
void mock_atu_add_region_CMockReturnMemThruPtr_region_idx(UNITY_LINE_TYPE cmock_line, uint8_t* region_idx, size_t cmock_size);
#define mock_atu_add_region_IgnoreArg_region() mock_atu_add_region_CMockIgnoreArg_region(__LINE__)
void mock_atu_add_region_CMockIgnoreArg_region(UNITY_LINE_TYPE cmock_line);
#define mock_atu_add_region_IgnoreArg_atu_device_id() mock_atu_add_region_CMockIgnoreArg_atu_device_id(__LINE__)
void mock_atu_add_region_CMockIgnoreArg_atu_device_id(UNITY_LINE_TYPE cmock_line);
#define mock_atu_add_region_IgnoreArg_region_idx() mock_atu_add_region_CMockIgnoreArg_region_idx(__LINE__)
void mock_atu_add_region_CMockIgnoreArg_region_idx(UNITY_LINE_TYPE cmock_line);
#define mock_atu_remove_region_IgnoreAndReturn(cmock_retval) mock_atu_remove_region_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void mock_atu_remove_region_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define mock_atu_remove_region_StopIgnore() mock_atu_remove_region_CMockStopIgnore()
void mock_atu_remove_region_CMockStopIgnore(void);
#define mock_atu_remove_region_ExpectAnyArgsAndReturn(cmock_retval) mock_atu_remove_region_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void mock_atu_remove_region_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define mock_atu_remove_region_ExpectAndReturn(region_idx, atu_device_id, requester_id, cmock_retval) mock_atu_remove_region_CMockExpectAndReturn(__LINE__, region_idx, atu_device_id, requester_id, cmock_retval)
void mock_atu_remove_region_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t region_idx, fwk_id_t atu_device_id, fwk_id_t requester_id, int cmock_to_return);
typedef int (* CMOCK_mock_atu_remove_region_CALLBACK)(uint8_t region_idx, fwk_id_t atu_device_id, fwk_id_t requester_id, int cmock_num_calls);
void mock_atu_remove_region_AddCallback(CMOCK_mock_atu_remove_region_CALLBACK Callback);
void mock_atu_remove_region_Stub(CMOCK_mock_atu_remove_region_CALLBACK Callback);
#define mock_atu_remove_region_StubWithCallback mock_atu_remove_region_Stub
#define mock_atu_remove_region_IgnoreArg_region_idx() mock_atu_remove_region_CMockIgnoreArg_region_idx(__LINE__)
void mock_atu_remove_region_CMockIgnoreArg_region_idx(UNITY_LINE_TYPE cmock_line);
#define mock_atu_remove_region_IgnoreArg_atu_device_id() mock_atu_remove_region_CMockIgnoreArg_atu_device_id(__LINE__)
void mock_atu_remove_region_CMockIgnoreArg_atu_device_id(UNITY_LINE_TYPE cmock_line);
#define mock_atu_remove_region_IgnoreArg_requester_id() mock_atu_remove_region_CMockIgnoreArg_requester_id(__LINE__)
void mock_atu_remove_region_CMockIgnoreArg_requester_id(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
