/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_atu_mmio_extra.h"

static const char* CMockString_atu_device_id = "atu_device_id";
static const char* CMockString_mock_atu_add_region = "mock_atu_add_region";
static const char* CMockString_mock_atu_remove_region = "mock_atu_remove_region";
static const char* CMockString_region = "region";
static const char* CMockString_region_idx = "region_idx";
static const char* CMockString_requester_id = "requester_id";

typedef struct _CMOCK_mock_atu_add_region_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct atu_region_map* Expected_region;
  fwk_id_t Expected_atu_device_id;
  uint8_t* Expected_region_idx;
  int Expected_region_Depth;
  int Expected_region_idx_Depth;
  char ReturnThruPtr_region_idx_Used;
  uint8_t* ReturnThruPtr_region_idx_Val;
  size_t ReturnThruPtr_region_idx_Size;
  char IgnoreArg_region;
  char IgnoreArg_atu_device_id;
  char IgnoreArg_region_idx;

} CMOCK_mock_atu_add_region_CALL_INSTANCE;

typedef struct _CMOCK_mock_atu_remove_region_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uint8_t Expected_region_idx;
  fwk_id_t Expected_atu_device_id;
  fwk_id_t Expected_requester_id;
  char IgnoreArg_region_idx;
  char IgnoreArg_atu_device_id;
  char IgnoreArg_requester_id;

} CMOCK_mock_atu_remove_region_CALL_INSTANCE;

static struct Mockmod_atu_mmio_extraInstance
{
  char mock_atu_add_region_IgnoreBool;
  int mock_atu_add_region_FinalReturn;
  char mock_atu_add_region_CallbackBool;
  CMOCK_mock_atu_add_region_CALLBACK mock_atu_add_region_CallbackFunctionPointer;
  int mock_atu_add_region_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mock_atu_add_region_CallInstance;
  char mock_atu_remove_region_IgnoreBool;
  int mock_atu_remove_region_FinalReturn;
  char mock_atu_remove_region_CallbackBool;
  CMOCK_mock_atu_remove_region_CALLBACK mock_atu_remove_region_CallbackFunctionPointer;
  int mock_atu_remove_region_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mock_atu_remove_region_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_atu_mmio_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.mock_atu_add_region_CallInstance;
  if (Mock.mock_atu_add_region_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mock_atu_add_region);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mock_atu_add_region_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.mock_atu_remove_region_CallInstance;
  if (Mock.mock_atu_remove_region_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mock_atu_remove_region);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mock_atu_remove_region_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_atu_mmio_extra_Init(void)
{
  Mockmod_atu_mmio_extra_Destroy();
}

void Mockmod_atu_mmio_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int mock_atu_add_region(const struct atu_region_map* region, fwk_id_t atu_device_id, uint8_t* region_idx)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mock_atu_add_region);
  cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mock_atu_add_region_CallInstance);
  Mock.mock_atu_add_region_CallInstance = CMock_Guts_MemNext(Mock.mock_atu_add_region_CallInstance);
  if (Mock.mock_atu_add_region_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mock_atu_add_region_FinalReturn;
    Mock.mock_atu_add_region_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mock_atu_add_region_CallbackBool &&
      Mock.mock_atu_add_region_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mock_atu_add_region_CallbackFunctionPointer(region, atu_device_id, region_idx, Mock.mock_atu_add_region_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_region)
  {
    UNITY_SET_DETAILS(CMockString_mock_atu_add_region,CMockString_region);
    if (cmock_call_instance->Expected_region == NULL)
      { UNITY_TEST_ASSERT_NULL(region, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_region), (void*)(region), sizeof(const struct atu_region_map), cmock_call_instance->Expected_region_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_atu_device_id)
  {
    UNITY_SET_DETAILS(CMockString_mock_atu_add_region,CMockString_atu_device_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_atu_device_id), (void*)(&atu_device_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_region_idx)
  {
    UNITY_SET_DETAILS(CMockString_mock_atu_add_region,CMockString_region_idx);
    if (cmock_call_instance->Expected_region_idx == NULL)
      { UNITY_TEST_ASSERT_NULL(region_idx, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_region_idx, region_idx, cmock_call_instance->Expected_region_idx_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.mock_atu_add_region_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mock_atu_add_region_CallbackFunctionPointer(region, atu_device_id, region_idx, Mock.mock_atu_add_region_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_region_idx_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(region_idx, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)region_idx, (void*)cmock_call_instance->ReturnThruPtr_region_idx_Val,
      cmock_call_instance->ReturnThruPtr_region_idx_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mock_atu_add_region(CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance, const struct atu_region_map* region, int region_Depth, fwk_id_t atu_device_id, uint8_t* region_idx, int region_idx_Depth);
void CMockExpectParameters_mock_atu_add_region(CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance, const struct atu_region_map* region, int region_Depth, fwk_id_t atu_device_id, uint8_t* region_idx, int region_idx_Depth)
{
  cmock_call_instance->Expected_region = region;
  cmock_call_instance->Expected_region_Depth = region_Depth;
  cmock_call_instance->IgnoreArg_region = 0;
  memcpy((void*)(&cmock_call_instance->Expected_atu_device_id), (void*)(&atu_device_id),
         sizeof(fwk_id_t[sizeof(atu_device_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_atu_device_id = 0;
  cmock_call_instance->Expected_region_idx = region_idx;
  cmock_call_instance->Expected_region_idx_Depth = region_idx_Depth;
  cmock_call_instance->IgnoreArg_region_idx = 0;
  cmock_call_instance->ReturnThruPtr_region_idx_Used = 0;
}

void mock_atu_add_region_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_atu_add_region_CALL_INSTANCE));
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_atu_add_region_CallInstance = CMock_Guts_MemChain(Mock.mock_atu_add_region_CallInstance, cmock_guts_index);
  Mock.mock_atu_add_region_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mock_atu_add_region_IgnoreBool = (char)1;
}

void mock_atu_add_region_CMockStopIgnore(void)
{
  if(Mock.mock_atu_add_region_IgnoreBool)
    Mock.mock_atu_add_region_CallInstance = CMock_Guts_MemNext(Mock.mock_atu_add_region_CallInstance);
  Mock.mock_atu_add_region_IgnoreBool = (char)0;
}

void mock_atu_add_region_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_atu_add_region_CALL_INSTANCE));
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_atu_add_region_CallInstance = CMock_Guts_MemChain(Mock.mock_atu_add_region_CallInstance, cmock_guts_index);
  Mock.mock_atu_add_region_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mock_atu_add_region_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct atu_region_map* region, fwk_id_t atu_device_id, uint8_t* region_idx, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_atu_add_region_CALL_INSTANCE));
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_atu_add_region_CallInstance = CMock_Guts_MemChain(Mock.mock_atu_add_region_CallInstance, cmock_guts_index);
  Mock.mock_atu_add_region_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mock_atu_add_region(cmock_call_instance, region, 1, atu_device_id, region_idx, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mock_atu_add_region_AddCallback(CMOCK_mock_atu_add_region_CALLBACK Callback)
{
  Mock.mock_atu_add_region_IgnoreBool = (char)0;
  Mock.mock_atu_add_region_CallbackBool = (char)1;
  Mock.mock_atu_add_region_CallbackFunctionPointer = Callback;
}

void mock_atu_add_region_Stub(CMOCK_mock_atu_add_region_CALLBACK Callback)
{
  Mock.mock_atu_add_region_IgnoreBool = (char)0;
  Mock.mock_atu_add_region_CallbackBool = (char)0;
  Mock.mock_atu_add_region_CallbackFunctionPointer = Callback;
}

void mock_atu_add_region_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const struct atu_region_map* region, int region_Depth, fwk_id_t atu_device_id, uint8_t* region_idx, int region_idx_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_atu_add_region_CALL_INSTANCE));
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_atu_add_region_CallInstance = CMock_Guts_MemChain(Mock.mock_atu_add_region_CallInstance, cmock_guts_index);
  Mock.mock_atu_add_region_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mock_atu_add_region(cmock_call_instance, region, region_Depth, atu_device_id, region_idx, region_idx_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mock_atu_add_region_CMockReturnMemThruPtr_region_idx(UNITY_LINE_TYPE cmock_line, uint8_t* region_idx, size_t cmock_size)
{
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_atu_add_region_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_region_idx_Used = 1;
  cmock_call_instance->ReturnThruPtr_region_idx_Val = region_idx;
  cmock_call_instance->ReturnThruPtr_region_idx_Size = cmock_size;
}

void mock_atu_add_region_CMockIgnoreArg_region(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_atu_add_region_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_region = 1;
}

void mock_atu_add_region_CMockIgnoreArg_atu_device_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_atu_add_region_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_atu_device_id = 1;
}

void mock_atu_add_region_CMockIgnoreArg_region_idx(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_atu_add_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_add_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_atu_add_region_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_region_idx = 1;
}

int mock_atu_remove_region(uint8_t region_idx, fwk_id_t atu_device_id, fwk_id_t requester_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mock_atu_remove_region);
  cmock_call_instance = (CMOCK_mock_atu_remove_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mock_atu_remove_region_CallInstance);
  Mock.mock_atu_remove_region_CallInstance = CMock_Guts_MemNext(Mock.mock_atu_remove_region_CallInstance);
  if (Mock.mock_atu_remove_region_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mock_atu_remove_region_FinalReturn;
    Mock.mock_atu_remove_region_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mock_atu_remove_region_CallbackBool &&
      Mock.mock_atu_remove_region_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mock_atu_remove_region_CallbackFunctionPointer(region_idx, atu_device_id, requester_id, Mock.mock_atu_remove_region_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_region_idx)
  {
    UNITY_SET_DETAILS(CMockString_mock_atu_remove_region,CMockString_region_idx);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_region_idx, region_idx, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_atu_device_id)
  {
    UNITY_SET_DETAILS(CMockString_mock_atu_remove_region,CMockString_atu_device_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_atu_device_id), (void*)(&atu_device_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_requester_id)
  {
    UNITY_SET_DETAILS(CMockString_mock_atu_remove_region,CMockString_requester_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_requester_id), (void*)(&requester_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.mock_atu_remove_region_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mock_atu_remove_region_CallbackFunctionPointer(region_idx, atu_device_id, requester_id, Mock.mock_atu_remove_region_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mock_atu_remove_region(CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance, uint8_t region_idx, fwk_id_t atu_device_id, fwk_id_t requester_id);
void CMockExpectParameters_mock_atu_remove_region(CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance, uint8_t region_idx, fwk_id_t atu_device_id, fwk_id_t requester_id)
{
  cmock_call_instance->Expected_region_idx = region_idx;
  cmock_call_instance->IgnoreArg_region_idx = 0;
  memcpy((void*)(&cmock_call_instance->Expected_atu_device_id), (void*)(&atu_device_id),
         sizeof(fwk_id_t[sizeof(atu_device_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_atu_device_id = 0;
  memcpy((void*)(&cmock_call_instance->Expected_requester_id), (void*)(&requester_id),
         sizeof(fwk_id_t[sizeof(requester_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_requester_id = 0;
}

void mock_atu_remove_region_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_atu_remove_region_CALL_INSTANCE));
  CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_remove_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_atu_remove_region_CallInstance = CMock_Guts_MemChain(Mock.mock_atu_remove_region_CallInstance, cmock_guts_index);
  Mock.mock_atu_remove_region_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mock_atu_remove_region_IgnoreBool = (char)1;
}

void mock_atu_remove_region_CMockStopIgnore(void)
{
  if(Mock.mock_atu_remove_region_IgnoreBool)
    Mock.mock_atu_remove_region_CallInstance = CMock_Guts_MemNext(Mock.mock_atu_remove_region_CallInstance);
  Mock.mock_atu_remove_region_IgnoreBool = (char)0;
}

void mock_atu_remove_region_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_atu_remove_region_CALL_INSTANCE));
  CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_remove_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_atu_remove_region_CallInstance = CMock_Guts_MemChain(Mock.mock_atu_remove_region_CallInstance, cmock_guts_index);
  Mock.mock_atu_remove_region_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mock_atu_remove_region_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t region_idx, fwk_id_t atu_device_id, fwk_id_t requester_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_atu_remove_region_CALL_INSTANCE));
  CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_remove_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_atu_remove_region_CallInstance = CMock_Guts_MemChain(Mock.mock_atu_remove_region_CallInstance, cmock_guts_index);
  Mock.mock_atu_remove_region_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mock_atu_remove_region(cmock_call_instance, region_idx, atu_device_id, requester_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mock_atu_remove_region_AddCallback(CMOCK_mock_atu_remove_region_CALLBACK Callback)
{
  Mock.mock_atu_remove_region_IgnoreBool = (char)0;
  Mock.mock_atu_remove_region_CallbackBool = (char)1;
  Mock.mock_atu_remove_region_CallbackFunctionPointer = Callback;
}

void mock_atu_remove_region_Stub(CMOCK_mock_atu_remove_region_CALLBACK Callback)
{
  Mock.mock_atu_remove_region_IgnoreBool = (char)0;
  Mock.mock_atu_remove_region_CallbackBool = (char)0;
  Mock.mock_atu_remove_region_CallbackFunctionPointer = Callback;
}

void mock_atu_remove_region_CMockIgnoreArg_region_idx(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_remove_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_atu_remove_region_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_region_idx = 1;
}

void mock_atu_remove_region_CMockIgnoreArg_atu_device_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_remove_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_atu_remove_region_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_atu_device_id = 1;
}

void mock_atu_remove_region_CMockIgnoreArg_requester_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_atu_remove_region_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_atu_remove_region_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_atu_remove_region_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_requester_id = 1;
}

