/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_posix_transport_extra.h"

static const char* CMockString_device_id = "device_id";
static const char* CMockString_listener_signal_message = "listener_signal_message";
static const char* CMockString_message = "message";
static const char* CMockString_posix_dev_get_message = "posix_dev_get_message";
static const char* CMockString_posix_dev_send_message = "posix_dev_send_message";
static const char* CMockString_service_id = "service_id";

typedef struct _CMOCK_posix_dev_get_message_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  struct mod_posix_transport_message* Expected_message;
  fwk_id_t Expected_device_id;
  int Expected_message_Depth;
  char ReturnThruPtr_message_Used;
  struct mod_posix_transport_message* ReturnThruPtr_message_Val;
  size_t ReturnThruPtr_message_Size;
  char IgnoreArg_message;
  char IgnoreArg_device_id;

} CMOCK_posix_dev_get_message_CALL_INSTANCE;

typedef struct _CMOCK_posix_dev_send_message_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  struct mod_posix_transport_message* Expected_message;
  fwk_id_t Expected_device_id;
  int Expected_message_Depth;
  char ReturnThruPtr_message_Used;
  struct mod_posix_transport_message* ReturnThruPtr_message_Val;
  size_t ReturnThruPtr_message_Size;
  char IgnoreArg_message;
  char IgnoreArg_device_id;

} CMOCK_posix_dev_send_message_CALL_INSTANCE;

typedef struct _CMOCK_listener_signal_message_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_service_id;
  char IgnoreArg_service_id;

} CMOCK_listener_signal_message_CALL_INSTANCE;

static struct Mockmod_posix_transport_extraInstance
{
  char posix_dev_get_message_IgnoreBool;
  int posix_dev_get_message_FinalReturn;
  char posix_dev_get_message_CallbackBool;
  CMOCK_posix_dev_get_message_CALLBACK posix_dev_get_message_CallbackFunctionPointer;
  int posix_dev_get_message_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE posix_dev_get_message_CallInstance;
  char posix_dev_send_message_IgnoreBool;
  int posix_dev_send_message_FinalReturn;
  char posix_dev_send_message_CallbackBool;
  CMOCK_posix_dev_send_message_CALLBACK posix_dev_send_message_CallbackFunctionPointer;
  int posix_dev_send_message_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE posix_dev_send_message_CallInstance;
  char listener_signal_message_IgnoreBool;
  int listener_signal_message_FinalReturn;
  char listener_signal_message_CallbackBool;
  CMOCK_listener_signal_message_CALLBACK listener_signal_message_CallbackFunctionPointer;
  int listener_signal_message_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE listener_signal_message_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_posix_transport_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.posix_dev_get_message_CallInstance;
  if (Mock.posix_dev_get_message_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_posix_dev_get_message);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.posix_dev_get_message_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.posix_dev_send_message_CallInstance;
  if (Mock.posix_dev_send_message_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_posix_dev_send_message);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.posix_dev_send_message_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.listener_signal_message_CallInstance;
  if (Mock.listener_signal_message_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_listener_signal_message);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.listener_signal_message_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_posix_transport_extra_Init(void)
{
  Mockmod_posix_transport_extra_Destroy();
}

void Mockmod_posix_transport_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int posix_dev_get_message(struct mod_posix_transport_message* message, fwk_id_t device_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_posix_dev_get_message);
  cmock_call_instance = (CMOCK_posix_dev_get_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.posix_dev_get_message_CallInstance);
  Mock.posix_dev_get_message_CallInstance = CMock_Guts_MemNext(Mock.posix_dev_get_message_CallInstance);
  if (Mock.posix_dev_get_message_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.posix_dev_get_message_FinalReturn;
    Mock.posix_dev_get_message_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.posix_dev_get_message_CallbackBool &&
      Mock.posix_dev_get_message_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.posix_dev_get_message_CallbackFunctionPointer(message, device_id, Mock.posix_dev_get_message_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_message)
  {
    UNITY_SET_DETAILS(CMockString_posix_dev_get_message,CMockString_message);
    if (cmock_call_instance->Expected_message == NULL)
      { UNITY_TEST_ASSERT_NULL(message, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_message), (void*)(message), sizeof(struct mod_posix_transport_message), cmock_call_instance->Expected_message_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_device_id)
  {
    UNITY_SET_DETAILS(CMockString_posix_dev_get_message,CMockString_device_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_device_id), (void*)(&device_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.posix_dev_get_message_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.posix_dev_get_message_CallbackFunctionPointer(message, device_id, Mock.posix_dev_get_message_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_message_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(message, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)message, (void*)cmock_call_instance->ReturnThruPtr_message_Val,
      cmock_call_instance->ReturnThruPtr_message_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_posix_dev_get_message(CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance, struct mod_posix_transport_message* message, int message_Depth, fwk_id_t device_id);
void CMockExpectParameters_posix_dev_get_message(CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance, struct mod_posix_transport_message* message, int message_Depth, fwk_id_t device_id)
{
  cmock_call_instance->Expected_message = message;
  cmock_call_instance->Expected_message_Depth = message_Depth;
  cmock_call_instance->IgnoreArg_message = 0;
  cmock_call_instance->ReturnThruPtr_message_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_device_id), (void*)(&device_id),
         sizeof(fwk_id_t[sizeof(device_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_device_id = 0;
}

void posix_dev_get_message_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_posix_dev_get_message_CALL_INSTANCE));
  CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_get_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.posix_dev_get_message_CallInstance = CMock_Guts_MemChain(Mock.posix_dev_get_message_CallInstance, cmock_guts_index);
  Mock.posix_dev_get_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.posix_dev_get_message_IgnoreBool = (char)1;
}

void posix_dev_get_message_CMockStopIgnore(void)
{
  if(Mock.posix_dev_get_message_IgnoreBool)
    Mock.posix_dev_get_message_CallInstance = CMock_Guts_MemNext(Mock.posix_dev_get_message_CallInstance);
  Mock.posix_dev_get_message_IgnoreBool = (char)0;
}

void posix_dev_get_message_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_posix_dev_get_message_CALL_INSTANCE));
  CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_get_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.posix_dev_get_message_CallInstance = CMock_Guts_MemChain(Mock.posix_dev_get_message_CallInstance, cmock_guts_index);
  Mock.posix_dev_get_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void posix_dev_get_message_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, fwk_id_t device_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_posix_dev_get_message_CALL_INSTANCE));
  CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_get_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.posix_dev_get_message_CallInstance = CMock_Guts_MemChain(Mock.posix_dev_get_message_CallInstance, cmock_guts_index);
  Mock.posix_dev_get_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_posix_dev_get_message(cmock_call_instance, message, 1, device_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void posix_dev_get_message_AddCallback(CMOCK_posix_dev_get_message_CALLBACK Callback)
{
  Mock.posix_dev_get_message_IgnoreBool = (char)0;
  Mock.posix_dev_get_message_CallbackBool = (char)1;
  Mock.posix_dev_get_message_CallbackFunctionPointer = Callback;
}

void posix_dev_get_message_Stub(CMOCK_posix_dev_get_message_CALLBACK Callback)
{
  Mock.posix_dev_get_message_IgnoreBool = (char)0;
  Mock.posix_dev_get_message_CallbackBool = (char)0;
  Mock.posix_dev_get_message_CallbackFunctionPointer = Callback;
}

void posix_dev_get_message_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, int message_Depth, fwk_id_t device_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_posix_dev_get_message_CALL_INSTANCE));
  CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_get_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.posix_dev_get_message_CallInstance = CMock_Guts_MemChain(Mock.posix_dev_get_message_CallInstance, cmock_guts_index);
  Mock.posix_dev_get_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_posix_dev_get_message(cmock_call_instance, message, message_Depth, device_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void posix_dev_get_message_CMockReturnMemThruPtr_message(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, size_t cmock_size)
{
  CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_get_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.posix_dev_get_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_message_Used = 1;
  cmock_call_instance->ReturnThruPtr_message_Val = message;
  cmock_call_instance->ReturnThruPtr_message_Size = cmock_size;
}

void posix_dev_get_message_CMockIgnoreArg_message(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_get_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.posix_dev_get_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_message = 1;
}

void posix_dev_get_message_CMockIgnoreArg_device_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_posix_dev_get_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_get_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.posix_dev_get_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_device_id = 1;
}

int posix_dev_send_message(struct mod_posix_transport_message* message, fwk_id_t device_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_posix_dev_send_message);
  cmock_call_instance = (CMOCK_posix_dev_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.posix_dev_send_message_CallInstance);
  Mock.posix_dev_send_message_CallInstance = CMock_Guts_MemNext(Mock.posix_dev_send_message_CallInstance);
  if (Mock.posix_dev_send_message_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.posix_dev_send_message_FinalReturn;
    Mock.posix_dev_send_message_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.posix_dev_send_message_CallbackBool &&
      Mock.posix_dev_send_message_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.posix_dev_send_message_CallbackFunctionPointer(message, device_id, Mock.posix_dev_send_message_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_message)
  {
    UNITY_SET_DETAILS(CMockString_posix_dev_send_message,CMockString_message);
    if (cmock_call_instance->Expected_message == NULL)
      { UNITY_TEST_ASSERT_NULL(message, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_message), (void*)(message), sizeof(struct mod_posix_transport_message), cmock_call_instance->Expected_message_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_device_id)
  {
    UNITY_SET_DETAILS(CMockString_posix_dev_send_message,CMockString_device_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_device_id), (void*)(&device_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.posix_dev_send_message_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.posix_dev_send_message_CallbackFunctionPointer(message, device_id, Mock.posix_dev_send_message_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_message_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(message, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)message, (void*)cmock_call_instance->ReturnThruPtr_message_Val,
      cmock_call_instance->ReturnThruPtr_message_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_posix_dev_send_message(CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance, struct mod_posix_transport_message* message, int message_Depth, fwk_id_t device_id);
void CMockExpectParameters_posix_dev_send_message(CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance, struct mod_posix_transport_message* message, int message_Depth, fwk_id_t device_id)
{
  cmock_call_instance->Expected_message = message;
  cmock_call_instance->Expected_message_Depth = message_Depth;
  cmock_call_instance->IgnoreArg_message = 0;
  cmock_call_instance->ReturnThruPtr_message_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_device_id), (void*)(&device_id),
         sizeof(fwk_id_t[sizeof(device_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_device_id = 0;
}

void posix_dev_send_message_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_posix_dev_send_message_CALL_INSTANCE));
  CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.posix_dev_send_message_CallInstance = CMock_Guts_MemChain(Mock.posix_dev_send_message_CallInstance, cmock_guts_index);
  Mock.posix_dev_send_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.posix_dev_send_message_IgnoreBool = (char)1;
}

void posix_dev_send_message_CMockStopIgnore(void)
{
  if(Mock.posix_dev_send_message_IgnoreBool)
    Mock.posix_dev_send_message_CallInstance = CMock_Guts_MemNext(Mock.posix_dev_send_message_CallInstance);
  Mock.posix_dev_send_message_IgnoreBool = (char)0;
}

void posix_dev_send_message_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_posix_dev_send_message_CALL_INSTANCE));
  CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.posix_dev_send_message_CallInstance = CMock_Guts_MemChain(Mock.posix_dev_send_message_CallInstance, cmock_guts_index);
  Mock.posix_dev_send_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void posix_dev_send_message_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, fwk_id_t device_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_posix_dev_send_message_CALL_INSTANCE));
  CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.posix_dev_send_message_CallInstance = CMock_Guts_MemChain(Mock.posix_dev_send_message_CallInstance, cmock_guts_index);
  Mock.posix_dev_send_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_posix_dev_send_message(cmock_call_instance, message, 1, device_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void posix_dev_send_message_AddCallback(CMOCK_posix_dev_send_message_CALLBACK Callback)
{
  Mock.posix_dev_send_message_IgnoreBool = (char)0;
  Mock.posix_dev_send_message_CallbackBool = (char)1;
  Mock.posix_dev_send_message_CallbackFunctionPointer = Callback;
}

void posix_dev_send_message_Stub(CMOCK_posix_dev_send_message_CALLBACK Callback)
{
  Mock.posix_dev_send_message_IgnoreBool = (char)0;
  Mock.posix_dev_send_message_CallbackBool = (char)0;
  Mock.posix_dev_send_message_CallbackFunctionPointer = Callback;
}

void posix_dev_send_message_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, int message_Depth, fwk_id_t device_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_posix_dev_send_message_CALL_INSTANCE));
  CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.posix_dev_send_message_CallInstance = CMock_Guts_MemChain(Mock.posix_dev_send_message_CallInstance, cmock_guts_index);
  Mock.posix_dev_send_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_posix_dev_send_message(cmock_call_instance, message, message_Depth, device_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void posix_dev_send_message_CMockReturnMemThruPtr_message(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, size_t cmock_size)
{
  CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.posix_dev_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_message_Used = 1;
  cmock_call_instance->ReturnThruPtr_message_Val = message;
  cmock_call_instance->ReturnThruPtr_message_Size = cmock_size;
}

void posix_dev_send_message_CMockIgnoreArg_message(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.posix_dev_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_message = 1;
}

void posix_dev_send_message_CMockIgnoreArg_device_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_posix_dev_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_posix_dev_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.posix_dev_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_device_id = 1;
}

int listener_signal_message(fwk_id_t service_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_listener_signal_message_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_listener_signal_message);
  cmock_call_instance = (CMOCK_listener_signal_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.listener_signal_message_CallInstance);
  Mock.listener_signal_message_CallInstance = CMock_Guts_MemNext(Mock.listener_signal_message_CallInstance);
  if (Mock.listener_signal_message_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.listener_signal_message_FinalReturn;
    Mock.listener_signal_message_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.listener_signal_message_CallbackBool &&
      Mock.listener_signal_message_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.listener_signal_message_CallbackFunctionPointer(service_id, Mock.listener_signal_message_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_service_id)
  {
    UNITY_SET_DETAILS(CMockString_listener_signal_message,CMockString_service_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.listener_signal_message_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.listener_signal_message_CallbackFunctionPointer(service_id, Mock.listener_signal_message_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_listener_signal_message(CMOCK_listener_signal_message_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id);
void CMockExpectParameters_listener_signal_message(CMOCK_listener_signal_message_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id),
         sizeof(fwk_id_t[sizeof(service_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_service_id = 0;
}

void listener_signal_message_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_listener_signal_message_CALL_INSTANCE));
  CMOCK_listener_signal_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_listener_signal_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.listener_signal_message_CallInstance = CMock_Guts_MemChain(Mock.listener_signal_message_CallInstance, cmock_guts_index);
  Mock.listener_signal_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.listener_signal_message_IgnoreBool = (char)1;
}

void listener_signal_message_CMockStopIgnore(void)
{
  if(Mock.listener_signal_message_IgnoreBool)
    Mock.listener_signal_message_CallInstance = CMock_Guts_MemNext(Mock.listener_signal_message_CallInstance);
  Mock.listener_signal_message_IgnoreBool = (char)0;
}

void listener_signal_message_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_listener_signal_message_CALL_INSTANCE));
  CMOCK_listener_signal_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_listener_signal_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.listener_signal_message_CallInstance = CMock_Guts_MemChain(Mock.listener_signal_message_CallInstance, cmock_guts_index);
  Mock.listener_signal_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void listener_signal_message_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_listener_signal_message_CALL_INSTANCE));
  CMOCK_listener_signal_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_listener_signal_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.listener_signal_message_CallInstance = CMock_Guts_MemChain(Mock.listener_signal_message_CallInstance, cmock_guts_index);
  Mock.listener_signal_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_listener_signal_message(cmock_call_instance, service_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void listener_signal_message_AddCallback(CMOCK_listener_signal_message_CALLBACK Callback)
{
  Mock.listener_signal_message_IgnoreBool = (char)0;
  Mock.listener_signal_message_CallbackBool = (char)1;
  Mock.listener_signal_message_CallbackFunctionPointer = Callback;
}

void listener_signal_message_Stub(CMOCK_listener_signal_message_CALLBACK Callback)
{
  Mock.listener_signal_message_IgnoreBool = (char)0;
  Mock.listener_signal_message_CallbackBool = (char)0;
  Mock.listener_signal_message_CallbackFunctionPointer = Callback;
}

void listener_signal_message_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_listener_signal_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_listener_signal_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.listener_signal_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_service_id = 1;
}

