/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMOD_POSIX_TRANSPORT_EXTRA_H
#define _MOCKMOD_POSIX_TRANSPORT_EXTRA_H

#include "unity.h"
#include "mod_posix_transport_extra.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmod_posix_transport_extra_Init(void);
void Mockmod_posix_transport_extra_Destroy(void);
void Mockmod_posix_transport_extra_Verify(void);




#define posix_dev_get_message_IgnoreAndReturn(cmock_retval) posix_dev_get_message_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void posix_dev_get_message_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define posix_dev_get_message_StopIgnore() posix_dev_get_message_CMockStopIgnore()
void posix_dev_get_message_CMockStopIgnore(void);
#define posix_dev_get_message_ExpectAnyArgsAndReturn(cmock_retval) posix_dev_get_message_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void posix_dev_get_message_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define posix_dev_get_message_ExpectAndReturn(message, device_id, cmock_retval) posix_dev_get_message_CMockExpectAndReturn(__LINE__, message, device_id, cmock_retval)
void posix_dev_get_message_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, fwk_id_t device_id, int cmock_to_return);
typedef int (* CMOCK_posix_dev_get_message_CALLBACK)(struct mod_posix_transport_message* message, fwk_id_t device_id, int cmock_num_calls);
void posix_dev_get_message_AddCallback(CMOCK_posix_dev_get_message_CALLBACK Callback);
void posix_dev_get_message_Stub(CMOCK_posix_dev_get_message_CALLBACK Callback);
#define posix_dev_get_message_StubWithCallback posix_dev_get_message_Stub
#define posix_dev_get_message_ExpectWithArrayAndReturn(message, message_Depth, device_id, cmock_retval) posix_dev_get_message_CMockExpectWithArrayAndReturn(__LINE__, message, message_Depth, device_id, cmock_retval)
void posix_dev_get_message_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, int message_Depth, fwk_id_t device_id, int cmock_to_return);
#define posix_dev_get_message_ReturnThruPtr_message(message) posix_dev_get_message_CMockReturnMemThruPtr_message(__LINE__, message, sizeof(struct mod_posix_transport_message))
#define posix_dev_get_message_ReturnArrayThruPtr_message(message, cmock_len) posix_dev_get_message_CMockReturnMemThruPtr_message(__LINE__, message, cmock_len * sizeof(*message))
#define posix_dev_get_message_ReturnMemThruPtr_message(message, cmock_size) posix_dev_get_message_CMockReturnMemThruPtr_message(__LINE__, message, cmock_size)
void posix_dev_get_message_CMockReturnMemThruPtr_message(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, size_t cmock_size);
#define posix_dev_get_message_IgnoreArg_message() posix_dev_get_message_CMockIgnoreArg_message(__LINE__)
void posix_dev_get_message_CMockIgnoreArg_message(UNITY_LINE_TYPE cmock_line);
#define posix_dev_get_message_IgnoreArg_device_id() posix_dev_get_message_CMockIgnoreArg_device_id(__LINE__)
void posix_dev_get_message_CMockIgnoreArg_device_id(UNITY_LINE_TYPE cmock_line);
#define posix_dev_send_message_IgnoreAndReturn(cmock_retval) posix_dev_send_message_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void posix_dev_send_message_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define posix_dev_send_message_StopIgnore() posix_dev_send_message_CMockStopIgnore()
void posix_dev_send_message_CMockStopIgnore(void);
#define posix_dev_send_message_ExpectAnyArgsAndReturn(cmock_retval) posix_dev_send_message_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void posix_dev_send_message_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define posix_dev_send_message_ExpectAndReturn(message, device_id, cmock_retval) posix_dev_send_message_CMockExpectAndReturn(__LINE__, message, device_id, cmock_retval)
void posix_dev_send_message_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, fwk_id_t device_id, int cmock_to_return);
typedef int (* CMOCK_posix_dev_send_message_CALLBACK)(struct mod_posix_transport_message* message, fwk_id_t device_id, int cmock_num_calls);
void posix_dev_send_message_AddCallback(CMOCK_posix_dev_send_message_CALLBACK Callback);
void posix_dev_send_message_Stub(CMOCK_posix_dev_send_message_CALLBACK Callback);
#define posix_dev_send_message_StubWithCallback posix_dev_send_message_Stub
#define posix_dev_send_message_ExpectWithArrayAndReturn(message, message_Depth, device_id, cmock_retval) posix_dev_send_message_CMockExpectWithArrayAndReturn(__LINE__, message, message_Depth, device_id, cmock_retval)
void posix_dev_send_message_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, int message_Depth, fwk_id_t device_id, int cmock_to_return);
#define posix_dev_send_message_ReturnThruPtr_message(message) posix_dev_send_message_CMockReturnMemThruPtr_message(__LINE__, message, sizeof(struct mod_posix_transport_message))
#define posix_dev_send_message_ReturnArrayThruPtr_message(message, cmock_len) posix_dev_send_message_CMockReturnMemThruPtr_message(__LINE__, message, cmock_len * sizeof(*message))
#define posix_dev_send_message_ReturnMemThruPtr_message(message, cmock_size) posix_dev_send_message_CMockReturnMemThruPtr_message(__LINE__, message, cmock_size)
void posix_dev_send_message_CMockReturnMemThruPtr_message(UNITY_LINE_TYPE cmock_line, struct mod_posix_transport_message* message, size_t cmock_size);
#define posix_dev_send_message_IgnoreArg_message() posix_dev_send_message_CMockIgnoreArg_message(__LINE__)
void posix_dev_send_message_CMockIgnoreArg_message(UNITY_LINE_TYPE cmock_line);
#define posix_dev_send_message_IgnoreArg_device_id() posix_dev_send_message_CMockIgnoreArg_device_id(__LINE__)
void posix_dev_send_message_CMockIgnoreArg_device_id(UNITY_LINE_TYPE cmock_line);
#define listener_signal_message_IgnoreAndReturn(cmock_retval) listener_signal_message_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void listener_signal_message_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define listener_signal_message_StopIgnore() listener_signal_message_CMockStopIgnore()
void listener_signal_message_CMockStopIgnore(void);
#define listener_signal_message_ExpectAnyArgsAndReturn(cmock_retval) listener_signal_message_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void listener_signal_message_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define listener_signal_message_ExpectAndReturn(service_id, cmock_retval) listener_signal_message_CMockExpectAndReturn(__LINE__, service_id, cmock_retval)
void listener_signal_message_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, int cmock_to_return);
typedef int (* CMOCK_listener_signal_message_CALLBACK)(fwk_id_t service_id, int cmock_num_calls);
void listener_signal_message_AddCallback(CMOCK_listener_signal_message_CALLBACK Callback);
void listener_signal_message_Stub(CMOCK_listener_signal_message_CALLBACK Callback);
#define listener_signal_message_StubWithCallback listener_signal_message_Stub
#define listener_signal_message_IgnoreArg_service_id() listener_signal_message_CMockIgnoreArg_service_id(__LINE__)
void listener_signal_message_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
