/*
 * Arm SCP/MCP Software
 * Copyright (c) 2025, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Description:
 *    SBISTC module configuration (multi-signal, per-fault FMU device/node).
 */

#include <mod_sbistc.h>

#include <fwk_module.h>

#include <stddef.h>

/* Fault IDs for SBISTC faults (platform-specific) */
enum {
    FLT_SBISTC_EQ_FAIL_CORE0,
    FLT_SBISTC_DEADLCK_CORE0,
    FLT_SBISTC_EQ_FAIL_CORE1,
    FLT_SBISTC_DEADLCK_CORE1,
    FLT_SBISTC_EQ_FAIL_CORE2,
    FLT_SBISTC_DEADLCK_CORE2,
    FLT_SBISTC_EQ_FAIL_CORE3,
    FLT_SBISTC_DEADLCK_CORE3,
    FLT_SBISTC_EQ_FAIL_CORE4,
    FLT_SBISTC_DEADLCK_CORE4,
    FLT_SBISTC_EQ_FAIL_CORE5,
    FLT_SBISTC_DEADLCK_CORE5,
    FLT_SBISTC_EQ_FAIL_CORE6,
    FLT_SBISTC_DEADLCK_CORE6,
    FLT_SBISTC_EQ_FAIL_CORE7,
    FLT_SBISTC_DEADLCK_CORE7,
    FLT_SBISTC_EQ_FAIL_CORE8,
    FLT_SBISTC_DEADLCK_CORE8,
    FLT_SBISTC_EQ_FAIL_CORE9,
    FLT_SBISTC_DEADLCK_CORE9,
    FLT_SBISTC_EQ_FAIL_CORE10,
    FLT_SBISTC_DEADLCK_CORE10,
    FLT_SBISTC_EQ_FAIL_CORE11,
    FLT_SBISTC_DEADLCK_CORE11,
    FLT_SBISTC_EQ_FAIL_CORE12,
    FLT_SBISTC_DEADLCK_CORE12,
    FLT_SBISTC_EQ_FAIL_CORE13,
    FLT_SBISTC_DEADLCK_CORE13,
    FLT_SBISTC_EQ_FAIL_CORE14,
    FLT_SBISTC_DEADLCK_CORE14,
    FLT_SBISTC_EQ_FAIL_CORE15,
    FLT_SBISTC_DEADLCK_CORE15,
    FLT_SBISTC_CNT
};

/* Node ID and device mapping based on your image */
struct sbistc_fault_config sbistc_faults[FLT_SBISTC_CNT + 1] = {
    [FLT_SBISTC_EQ_FAIL_CORE0] = { "SBISTC_EQ_FAIL_CORE0", 1, 4, NULL },
    [FLT_SBISTC_DEADLCK_CORE0] = { "SBISTC_DEADLCK_CORE0", 1, 5, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE1] = { "SBISTC_EQ_FAIL_CORE1", 1, 6, NULL },
    [FLT_SBISTC_DEADLCK_CORE1] = { "SBISTC_DEADLCK_CORE1", 1, 7, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE2] = { "SBISTC_EQ_FAIL_CORE2", 1, 8, NULL },
    [FLT_SBISTC_DEADLCK_CORE2] = { "SBISTC_DEADLCK_CORE2", 1, 9, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE3] = { "SBISTC_EQ_FAIL_CORE3", 1, 10, NULL },
    [FLT_SBISTC_DEADLCK_CORE3] = { "SBISTC_DEADLCK_CORE3", 1, 11, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE4] = { "SBISTC_EQ_FAIL_CORE4", 1, 16, NULL },
    [FLT_SBISTC_DEADLCK_CORE4] = { "SBISTC_DEADLCK_CORE4", 1, 17, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE5] = { "SBISTC_EQ_FAIL_CORE5", 1, 18, NULL },
    [FLT_SBISTC_DEADLCK_CORE5] = { "SBISTC_DEADLCK_CORE5", 1, 19, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE6] = { "SBISTC_EQ_FAIL_CORE6", 1, 20, NULL },
    [FLT_SBISTC_DEADLCK_CORE6] = { "SBISTC_DEADLCK_CORE6", 1, 21, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE7] = { "SBISTC_EQ_FAIL_CORE7", 1, 22, NULL },
    [FLT_SBISTC_DEADLCK_CORE7] = { "SBISTC_DEADLCK_CORE7", 1, 23, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE8] = { "SBISTC_EQ_FAIL_CORE8", 1, 28, NULL },
    [FLT_SBISTC_DEADLCK_CORE8] = { "SBISTC_DEADLCK_CORE8", 1, 29, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE9] = { "SBISTC_EQ_FAIL_CORE9", 1, 30, NULL },
    [FLT_SBISTC_DEADLCK_CORE9] = { "SBISTC_DEADLCK_CORE9", 1, 31, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE10] = { "SBISTC_EQ_FAIL_CORE10", 1, 32, NULL },
    [FLT_SBISTC_DEADLCK_CORE10] = { "SBISTC_DEADLCK_CORE10", 1, 33, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE11] = { "SBISTC_EQ_FAIL_CORE11", 1, 34, NULL },
    [FLT_SBISTC_DEADLCK_CORE11] = { "SBISTC_DEADLCK_CORE11", 1, 35, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE12] = { "SBISTC_EQ_FAIL_CORE12", 1, 40, NULL },
    [FLT_SBISTC_DEADLCK_CORE12] = { "SBISTC_DEADLCK_CORE12", 1, 41, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE13] = { "SBISTC_EQ_FAIL_CORE13", 1, 42, NULL },
    [FLT_SBISTC_DEADLCK_CORE13] = { "SBISTC_DEADLCK_CORE13", 1, 43, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE14] = { "SBISTC_EQ_FAIL_CORE14", 1, 44, NULL },
    [FLT_SBISTC_DEADLCK_CORE14] = { "SBISTC_DEADLCK_CORE14", 1, 45, NULL },
    [FLT_SBISTC_EQ_FAIL_CORE15] = { "SBISTC_EQ_FAIL_CORE15", 1, 46, NULL },
    [FLT_SBISTC_DEADLCK_CORE15] = { "SBISTC_DEADLCK_CORE15", 1, 47, NULL },
    [FLT_SBISTC_CNT] = { NULL, 0, 0, NULL }
};

/* Module config for SBISTC */
static struct mod_sbistc_config sbistc_mod_config = {
    .count = FLT_SBISTC_CNT,
    .flt_cfgs = sbistc_faults,
};

/* Framework module config */
const struct fwk_module_config config_sbistc = {
    .data = &sbistc_mod_config,
};
