/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTEST_FMU_EXTRAS_H
#define _MOCKTEST_FMU_EXTRAS_H

#include "unity.h"
#include "test_fmu_extras.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mocktest_fmu_extras_Init(void);
void Mocktest_fmu_extras_Destroy(void);
void Mocktest_fmu_extras_Verify(void);




#define test_fmu_set_enabled_IgnoreAndReturn(cmock_retval) test_fmu_set_enabled_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void test_fmu_set_enabled_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define test_fmu_set_enabled_StopIgnore() test_fmu_set_enabled_CMockStopIgnore()
void test_fmu_set_enabled_CMockStopIgnore(void);
#define test_fmu_set_enabled_ExpectAnyArgsAndReturn(cmock_retval) test_fmu_set_enabled_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void test_fmu_set_enabled_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define test_fmu_set_enabled_ExpectAndReturn(fault, enable, cmock_retval) test_fmu_set_enabled_CMockExpectAndReturn(__LINE__, fault, enable, cmock_retval)
void test_fmu_set_enabled_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct mod_fmu_fault* fault, bool enable, int cmock_to_return);
typedef int (* CMOCK_test_fmu_set_enabled_CALLBACK)(const struct mod_fmu_fault* fault, bool enable, int cmock_num_calls);
void test_fmu_set_enabled_AddCallback(CMOCK_test_fmu_set_enabled_CALLBACK Callback);
void test_fmu_set_enabled_Stub(CMOCK_test_fmu_set_enabled_CALLBACK Callback);
#define test_fmu_set_enabled_StubWithCallback test_fmu_set_enabled_Stub
#define test_fmu_set_enabled_ExpectWithArrayAndReturn(fault, fault_Depth, enable, cmock_retval) test_fmu_set_enabled_CMockExpectWithArrayAndReturn(__LINE__, fault, fault_Depth, enable, cmock_retval)
void test_fmu_set_enabled_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const struct mod_fmu_fault* fault, int fault_Depth, bool enable, int cmock_to_return);
#define test_fmu_set_enabled_IgnoreArg_fault() test_fmu_set_enabled_CMockIgnoreArg_fault(__LINE__)
void test_fmu_set_enabled_CMockIgnoreArg_fault(UNITY_LINE_TYPE cmock_line);
#define test_fmu_set_enabled_IgnoreArg_enable() test_fmu_set_enabled_CMockIgnoreArg_enable(__LINE__)
void test_fmu_set_enabled_CMockIgnoreArg_enable(UNITY_LINE_TYPE cmock_line);
#define test_fmu_get_count_IgnoreAndReturn(cmock_retval) test_fmu_get_count_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void test_fmu_get_count_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define test_fmu_get_count_StopIgnore() test_fmu_get_count_CMockStopIgnore()
void test_fmu_get_count_CMockStopIgnore(void);
#define test_fmu_get_count_ExpectAnyArgsAndReturn(cmock_retval) test_fmu_get_count_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void test_fmu_get_count_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define test_fmu_get_count_ExpectAndReturn(id, node, count, cmock_retval) test_fmu_get_count_CMockExpectAndReturn(__LINE__, id, node, count, cmock_retval)
void test_fmu_get_count_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint16_t node, uint8_t* count, int cmock_to_return);
typedef int (* CMOCK_test_fmu_get_count_CALLBACK)(fwk_id_t id, uint16_t node, uint8_t* count, int cmock_num_calls);
void test_fmu_get_count_AddCallback(CMOCK_test_fmu_get_count_CALLBACK Callback);
void test_fmu_get_count_Stub(CMOCK_test_fmu_get_count_CALLBACK Callback);
#define test_fmu_get_count_StubWithCallback test_fmu_get_count_Stub
#define test_fmu_get_count_ExpectWithArrayAndReturn(id, node, count, count_Depth, cmock_retval) test_fmu_get_count_CMockExpectWithArrayAndReturn(__LINE__, id, node, count, count_Depth, cmock_retval)
void test_fmu_get_count_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint16_t node, uint8_t* count, int count_Depth, int cmock_to_return);
#define test_fmu_get_count_ReturnThruPtr_count(count) test_fmu_get_count_CMockReturnMemThruPtr_count(__LINE__, count, sizeof(uint8_t))
#define test_fmu_get_count_ReturnArrayThruPtr_count(count, cmock_len) test_fmu_get_count_CMockReturnMemThruPtr_count(__LINE__, count, cmock_len * sizeof(*count))
#define test_fmu_get_count_ReturnMemThruPtr_count(count, cmock_size) test_fmu_get_count_CMockReturnMemThruPtr_count(__LINE__, count, cmock_size)
void test_fmu_get_count_CMockReturnMemThruPtr_count(UNITY_LINE_TYPE cmock_line, uint8_t* count, size_t cmock_size);
#define test_fmu_get_count_IgnoreArg_id() test_fmu_get_count_CMockIgnoreArg_id(__LINE__)
void test_fmu_get_count_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line);
#define test_fmu_get_count_IgnoreArg_node() test_fmu_get_count_CMockIgnoreArg_node(__LINE__)
void test_fmu_get_count_CMockIgnoreArg_node(UNITY_LINE_TYPE cmock_line);
#define test_fmu_get_count_IgnoreArg_count() test_fmu_get_count_CMockIgnoreArg_count(__LINE__)
void test_fmu_get_count_CMockIgnoreArg_count(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
