/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktest_fmu_extras.h"

static const char* CMockString_count = "count";
static const char* CMockString_enable = "enable";
static const char* CMockString_fault = "fault";
static const char* CMockString_id = "id";
static const char* CMockString_node = "node";
static const char* CMockString_test_fmu_get_count = "test_fmu_get_count";
static const char* CMockString_test_fmu_set_enabled = "test_fmu_set_enabled";

typedef struct _CMOCK_test_fmu_set_enabled_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct mod_fmu_fault* Expected_fault;
  bool Expected_enable;
  int Expected_fault_Depth;
  char IgnoreArg_fault;
  char IgnoreArg_enable;

} CMOCK_test_fmu_set_enabled_CALL_INSTANCE;

typedef struct _CMOCK_test_fmu_get_count_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint16_t Expected_node;
  uint8_t* Expected_count;
  int Expected_count_Depth;
  char ReturnThruPtr_count_Used;
  uint8_t* ReturnThruPtr_count_Val;
  size_t ReturnThruPtr_count_Size;
  char IgnoreArg_id;
  char IgnoreArg_node;
  char IgnoreArg_count;

} CMOCK_test_fmu_get_count_CALL_INSTANCE;

static struct Mocktest_fmu_extrasInstance
{
  char test_fmu_set_enabled_IgnoreBool;
  int test_fmu_set_enabled_FinalReturn;
  char test_fmu_set_enabled_CallbackBool;
  CMOCK_test_fmu_set_enabled_CALLBACK test_fmu_set_enabled_CallbackFunctionPointer;
  int test_fmu_set_enabled_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE test_fmu_set_enabled_CallInstance;
  char test_fmu_get_count_IgnoreBool;
  int test_fmu_get_count_FinalReturn;
  char test_fmu_get_count_CallbackBool;
  CMOCK_test_fmu_get_count_CALLBACK test_fmu_get_count_CallbackFunctionPointer;
  int test_fmu_get_count_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE test_fmu_get_count_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocktest_fmu_extras_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.test_fmu_set_enabled_CallInstance;
  if (Mock.test_fmu_set_enabled_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_test_fmu_set_enabled);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.test_fmu_set_enabled_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.test_fmu_get_count_CallInstance;
  if (Mock.test_fmu_get_count_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_test_fmu_get_count);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.test_fmu_get_count_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mocktest_fmu_extras_Init(void)
{
  Mocktest_fmu_extras_Destroy();
}

void Mocktest_fmu_extras_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int test_fmu_set_enabled(const struct mod_fmu_fault* fault, bool enable)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_test_fmu_set_enabled);
  cmock_call_instance = (CMOCK_test_fmu_set_enabled_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.test_fmu_set_enabled_CallInstance);
  Mock.test_fmu_set_enabled_CallInstance = CMock_Guts_MemNext(Mock.test_fmu_set_enabled_CallInstance);
  if (Mock.test_fmu_set_enabled_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.test_fmu_set_enabled_FinalReturn;
    Mock.test_fmu_set_enabled_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.test_fmu_set_enabled_CallbackBool &&
      Mock.test_fmu_set_enabled_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.test_fmu_set_enabled_CallbackFunctionPointer(fault, enable, Mock.test_fmu_set_enabled_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_fault)
  {
    UNITY_SET_DETAILS(CMockString_test_fmu_set_enabled,CMockString_fault);
    if (cmock_call_instance->Expected_fault == NULL)
      { UNITY_TEST_ASSERT_NULL(fault, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_fault), (void*)(fault), sizeof(const struct mod_fmu_fault), cmock_call_instance->Expected_fault_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_enable)
  {
    UNITY_SET_DETAILS(CMockString_test_fmu_set_enabled,CMockString_enable);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_enable, enable, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.test_fmu_set_enabled_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.test_fmu_set_enabled_CallbackFunctionPointer(fault, enable, Mock.test_fmu_set_enabled_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_test_fmu_set_enabled(CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance, const struct mod_fmu_fault* fault, int fault_Depth, bool enable);
void CMockExpectParameters_test_fmu_set_enabled(CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance, const struct mod_fmu_fault* fault, int fault_Depth, bool enable)
{
  cmock_call_instance->Expected_fault = fault;
  cmock_call_instance->Expected_fault_Depth = fault_Depth;
  cmock_call_instance->IgnoreArg_fault = 0;
  cmock_call_instance->Expected_enable = enable;
  cmock_call_instance->IgnoreArg_enable = 0;
}

void test_fmu_set_enabled_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_test_fmu_set_enabled_CALL_INSTANCE));
  CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_set_enabled_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.test_fmu_set_enabled_CallInstance = CMock_Guts_MemChain(Mock.test_fmu_set_enabled_CallInstance, cmock_guts_index);
  Mock.test_fmu_set_enabled_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.test_fmu_set_enabled_IgnoreBool = (char)1;
}

void test_fmu_set_enabled_CMockStopIgnore(void)
{
  if(Mock.test_fmu_set_enabled_IgnoreBool)
    Mock.test_fmu_set_enabled_CallInstance = CMock_Guts_MemNext(Mock.test_fmu_set_enabled_CallInstance);
  Mock.test_fmu_set_enabled_IgnoreBool = (char)0;
}

void test_fmu_set_enabled_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_test_fmu_set_enabled_CALL_INSTANCE));
  CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_set_enabled_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.test_fmu_set_enabled_CallInstance = CMock_Guts_MemChain(Mock.test_fmu_set_enabled_CallInstance, cmock_guts_index);
  Mock.test_fmu_set_enabled_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void test_fmu_set_enabled_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct mod_fmu_fault* fault, bool enable, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_test_fmu_set_enabled_CALL_INSTANCE));
  CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_set_enabled_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.test_fmu_set_enabled_CallInstance = CMock_Guts_MemChain(Mock.test_fmu_set_enabled_CallInstance, cmock_guts_index);
  Mock.test_fmu_set_enabled_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_test_fmu_set_enabled(cmock_call_instance, fault, 1, enable);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void test_fmu_set_enabled_AddCallback(CMOCK_test_fmu_set_enabled_CALLBACK Callback)
{
  Mock.test_fmu_set_enabled_IgnoreBool = (char)0;
  Mock.test_fmu_set_enabled_CallbackBool = (char)1;
  Mock.test_fmu_set_enabled_CallbackFunctionPointer = Callback;
}

void test_fmu_set_enabled_Stub(CMOCK_test_fmu_set_enabled_CALLBACK Callback)
{
  Mock.test_fmu_set_enabled_IgnoreBool = (char)0;
  Mock.test_fmu_set_enabled_CallbackBool = (char)0;
  Mock.test_fmu_set_enabled_CallbackFunctionPointer = Callback;
}

void test_fmu_set_enabled_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const struct mod_fmu_fault* fault, int fault_Depth, bool enable, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_test_fmu_set_enabled_CALL_INSTANCE));
  CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_set_enabled_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.test_fmu_set_enabled_CallInstance = CMock_Guts_MemChain(Mock.test_fmu_set_enabled_CallInstance, cmock_guts_index);
  Mock.test_fmu_set_enabled_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_test_fmu_set_enabled(cmock_call_instance, fault, fault_Depth, enable);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void test_fmu_set_enabled_CMockIgnoreArg_fault(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_set_enabled_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.test_fmu_set_enabled_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_fault = 1;
}

void test_fmu_set_enabled_CMockIgnoreArg_enable(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_test_fmu_set_enabled_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_set_enabled_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.test_fmu_set_enabled_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_enable = 1;
}

int test_fmu_get_count(fwk_id_t id, uint16_t node, uint8_t* count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_test_fmu_get_count);
  cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.test_fmu_get_count_CallInstance);
  Mock.test_fmu_get_count_CallInstance = CMock_Guts_MemNext(Mock.test_fmu_get_count_CallInstance);
  if (Mock.test_fmu_get_count_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.test_fmu_get_count_FinalReturn;
    Mock.test_fmu_get_count_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.test_fmu_get_count_CallbackBool &&
      Mock.test_fmu_get_count_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.test_fmu_get_count_CallbackFunctionPointer(id, node, count, Mock.test_fmu_get_count_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_test_fmu_get_count,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_node)
  {
    UNITY_SET_DETAILS(CMockString_test_fmu_get_count,CMockString_node);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_node, node, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_count)
  {
    UNITY_SET_DETAILS(CMockString_test_fmu_get_count,CMockString_count);
    if (cmock_call_instance->Expected_count == NULL)
      { UNITY_TEST_ASSERT_NULL(count, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_count, count, cmock_call_instance->Expected_count_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.test_fmu_get_count_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.test_fmu_get_count_CallbackFunctionPointer(id, node, count, Mock.test_fmu_get_count_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_count_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(count, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)count, (void*)cmock_call_instance->ReturnThruPtr_count_Val,
      cmock_call_instance->ReturnThruPtr_count_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_test_fmu_get_count(CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint16_t node, uint8_t* count, int count_Depth);
void CMockExpectParameters_test_fmu_get_count(CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint16_t node, uint8_t* count, int count_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_node = node;
  cmock_call_instance->IgnoreArg_node = 0;
  cmock_call_instance->Expected_count = count;
  cmock_call_instance->Expected_count_Depth = count_Depth;
  cmock_call_instance->IgnoreArg_count = 0;
  cmock_call_instance->ReturnThruPtr_count_Used = 0;
}

void test_fmu_get_count_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_test_fmu_get_count_CALL_INSTANCE));
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.test_fmu_get_count_CallInstance = CMock_Guts_MemChain(Mock.test_fmu_get_count_CallInstance, cmock_guts_index);
  Mock.test_fmu_get_count_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.test_fmu_get_count_IgnoreBool = (char)1;
}

void test_fmu_get_count_CMockStopIgnore(void)
{
  if(Mock.test_fmu_get_count_IgnoreBool)
    Mock.test_fmu_get_count_CallInstance = CMock_Guts_MemNext(Mock.test_fmu_get_count_CallInstance);
  Mock.test_fmu_get_count_IgnoreBool = (char)0;
}

void test_fmu_get_count_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_test_fmu_get_count_CALL_INSTANCE));
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.test_fmu_get_count_CallInstance = CMock_Guts_MemChain(Mock.test_fmu_get_count_CallInstance, cmock_guts_index);
  Mock.test_fmu_get_count_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void test_fmu_get_count_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint16_t node, uint8_t* count, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_test_fmu_get_count_CALL_INSTANCE));
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.test_fmu_get_count_CallInstance = CMock_Guts_MemChain(Mock.test_fmu_get_count_CallInstance, cmock_guts_index);
  Mock.test_fmu_get_count_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_test_fmu_get_count(cmock_call_instance, id, node, count, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void test_fmu_get_count_AddCallback(CMOCK_test_fmu_get_count_CALLBACK Callback)
{
  Mock.test_fmu_get_count_IgnoreBool = (char)0;
  Mock.test_fmu_get_count_CallbackBool = (char)1;
  Mock.test_fmu_get_count_CallbackFunctionPointer = Callback;
}

void test_fmu_get_count_Stub(CMOCK_test_fmu_get_count_CALLBACK Callback)
{
  Mock.test_fmu_get_count_IgnoreBool = (char)0;
  Mock.test_fmu_get_count_CallbackBool = (char)0;
  Mock.test_fmu_get_count_CallbackFunctionPointer = Callback;
}

void test_fmu_get_count_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint16_t node, uint8_t* count, int count_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_test_fmu_get_count_CALL_INSTANCE));
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.test_fmu_get_count_CallInstance = CMock_Guts_MemChain(Mock.test_fmu_get_count_CallInstance, cmock_guts_index);
  Mock.test_fmu_get_count_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_test_fmu_get_count(cmock_call_instance, id, node, count, count_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void test_fmu_get_count_CMockReturnMemThruPtr_count(UNITY_LINE_TYPE cmock_line, uint8_t* count, size_t cmock_size)
{
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.test_fmu_get_count_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_count_Used = 1;
  cmock_call_instance->ReturnThruPtr_count_Val = count;
  cmock_call_instance->ReturnThruPtr_count_Size = cmock_size;
}

void test_fmu_get_count_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.test_fmu_get_count_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void test_fmu_get_count_CMockIgnoreArg_node(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.test_fmu_get_count_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_node = 1;
}

void test_fmu_get_count_CMockIgnoreArg_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_test_fmu_get_count_CALL_INSTANCE* cmock_call_instance = (CMOCK_test_fmu_get_count_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.test_fmu_get_count_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_count = 1;
}

