/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockscmi_power_capping_protocol.h"

static const char* CMockString_api = "api";
static const char* CMockString_api_id = "api_id";
static const char* CMockString_event = "event";
static const char* CMockString_pcapping_protocol_bind = "pcapping_protocol_bind";
static const char* CMockString_pcapping_protocol_process_bind_request = "pcapping_protocol_process_bind_request";
static const char* CMockString_pcapping_protocol_process_cap_pai_notify_event = "pcapping_protocol_process_cap_pai_notify_event";
static const char* CMockString_pcapping_protocol_process_measurements_notify_event = "pcapping_protocol_process_measurements_notify_event";
static const char* CMockString_pcapping_protocol_start = "pcapping_protocol_start";

typedef struct _CMOCK_pcapping_protocol_bind_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;

} CMOCK_pcapping_protocol_bind_CALL_INSTANCE;

typedef struct _CMOCK_pcapping_protocol_start_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;

} CMOCK_pcapping_protocol_start_CALL_INSTANCE;

typedef struct _CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_api_id;
  const void** Expected_api;
  int Expected_api_Depth;
  char ReturnThruPtr_api_Used;
  const void** ReturnThruPtr_api_Val;
  size_t ReturnThruPtr_api_Size;
  char IgnoreArg_api_id;
  char IgnoreArg_api;

} CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE;

typedef struct _CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_event* Expected_event;
  int Expected_event_Depth;
  char IgnoreArg_event;

} CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE;

typedef struct _CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_event* Expected_event;
  int Expected_event_Depth;
  char IgnoreArg_event;

} CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE;

static struct Mockscmi_power_capping_protocolInstance
{
  char pcapping_protocol_bind_IgnoreBool;
  int pcapping_protocol_bind_FinalReturn;
  char pcapping_protocol_bind_CallbackBool;
  CMOCK_pcapping_protocol_bind_CALLBACK pcapping_protocol_bind_CallbackFunctionPointer;
  int pcapping_protocol_bind_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pcapping_protocol_bind_CallInstance;
  char pcapping_protocol_start_IgnoreBool;
  int pcapping_protocol_start_FinalReturn;
  char pcapping_protocol_start_CallbackBool;
  CMOCK_pcapping_protocol_start_CALLBACK pcapping_protocol_start_CallbackFunctionPointer;
  int pcapping_protocol_start_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pcapping_protocol_start_CallInstance;
  char pcapping_protocol_process_bind_request_IgnoreBool;
  int pcapping_protocol_process_bind_request_FinalReturn;
  char pcapping_protocol_process_bind_request_CallbackBool;
  CMOCK_pcapping_protocol_process_bind_request_CALLBACK pcapping_protocol_process_bind_request_CallbackFunctionPointer;
  int pcapping_protocol_process_bind_request_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pcapping_protocol_process_bind_request_CallInstance;
  char pcapping_protocol_process_cap_pai_notify_event_IgnoreBool;
  int pcapping_protocol_process_cap_pai_notify_event_FinalReturn;
  char pcapping_protocol_process_cap_pai_notify_event_CallbackBool;
  CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALLBACK pcapping_protocol_process_cap_pai_notify_event_CallbackFunctionPointer;
  int pcapping_protocol_process_cap_pai_notify_event_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pcapping_protocol_process_cap_pai_notify_event_CallInstance;
  char pcapping_protocol_process_measurements_notify_event_IgnoreBool;
  int pcapping_protocol_process_measurements_notify_event_FinalReturn;
  char pcapping_protocol_process_measurements_notify_event_CallbackBool;
  CMOCK_pcapping_protocol_process_measurements_notify_event_CALLBACK pcapping_protocol_process_measurements_notify_event_CallbackFunctionPointer;
  int pcapping_protocol_process_measurements_notify_event_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pcapping_protocol_process_measurements_notify_event_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockscmi_power_capping_protocol_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.pcapping_protocol_bind_CallInstance;
  if (Mock.pcapping_protocol_bind_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_pcapping_protocol_bind);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.pcapping_protocol_bind_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.pcapping_protocol_start_CallInstance;
  if (Mock.pcapping_protocol_start_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_pcapping_protocol_start);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.pcapping_protocol_start_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.pcapping_protocol_process_bind_request_CallInstance;
  if (Mock.pcapping_protocol_process_bind_request_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_pcapping_protocol_process_bind_request);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.pcapping_protocol_process_bind_request_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance;
  if (Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_pcapping_protocol_process_cap_pai_notify_event);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.pcapping_protocol_process_measurements_notify_event_CallInstance;
  if (Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_pcapping_protocol_process_measurements_notify_event);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.pcapping_protocol_process_measurements_notify_event_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockscmi_power_capping_protocol_Init(void)
{
  Mockscmi_power_capping_protocol_Destroy();
}

void Mockscmi_power_capping_protocol_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int pcapping_protocol_bind(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pcapping_protocol_bind_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_pcapping_protocol_bind);
  cmock_call_instance = (CMOCK_pcapping_protocol_bind_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pcapping_protocol_bind_CallInstance);
  Mock.pcapping_protocol_bind_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_bind_CallInstance);
  if (Mock.pcapping_protocol_bind_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.pcapping_protocol_bind_FinalReturn;
    Mock.pcapping_protocol_bind_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.pcapping_protocol_bind_CallbackBool &&
      Mock.pcapping_protocol_bind_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.pcapping_protocol_bind_CallbackFunctionPointer(Mock.pcapping_protocol_bind_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.pcapping_protocol_bind_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.pcapping_protocol_bind_CallbackFunctionPointer(Mock.pcapping_protocol_bind_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void pcapping_protocol_bind_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_bind_CALL_INSTANCE));
  CMOCK_pcapping_protocol_bind_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_bind_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_bind_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_bind_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_bind_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.pcapping_protocol_bind_IgnoreBool = (char)1;
}

void pcapping_protocol_bind_CMockStopIgnore(void)
{
  if(Mock.pcapping_protocol_bind_IgnoreBool)
    Mock.pcapping_protocol_bind_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_bind_CallInstance);
  Mock.pcapping_protocol_bind_IgnoreBool = (char)0;
}

void pcapping_protocol_bind_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_bind_CALL_INSTANCE));
  CMOCK_pcapping_protocol_bind_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_bind_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_bind_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_bind_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_bind_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pcapping_protocol_bind_AddCallback(CMOCK_pcapping_protocol_bind_CALLBACK Callback)
{
  Mock.pcapping_protocol_bind_IgnoreBool = (char)0;
  Mock.pcapping_protocol_bind_CallbackBool = (char)1;
  Mock.pcapping_protocol_bind_CallbackFunctionPointer = Callback;
}

void pcapping_protocol_bind_Stub(CMOCK_pcapping_protocol_bind_CALLBACK Callback)
{
  Mock.pcapping_protocol_bind_IgnoreBool = (char)0;
  Mock.pcapping_protocol_bind_CallbackBool = (char)0;
  Mock.pcapping_protocol_bind_CallbackFunctionPointer = Callback;
}

int pcapping_protocol_start(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pcapping_protocol_start_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_pcapping_protocol_start);
  cmock_call_instance = (CMOCK_pcapping_protocol_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pcapping_protocol_start_CallInstance);
  Mock.pcapping_protocol_start_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_start_CallInstance);
  if (Mock.pcapping_protocol_start_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.pcapping_protocol_start_FinalReturn;
    Mock.pcapping_protocol_start_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.pcapping_protocol_start_CallbackBool &&
      Mock.pcapping_protocol_start_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.pcapping_protocol_start_CallbackFunctionPointer(Mock.pcapping_protocol_start_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.pcapping_protocol_start_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.pcapping_protocol_start_CallbackFunctionPointer(Mock.pcapping_protocol_start_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void pcapping_protocol_start_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_start_CALL_INSTANCE));
  CMOCK_pcapping_protocol_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_start_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_start_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_start_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.pcapping_protocol_start_IgnoreBool = (char)1;
}

void pcapping_protocol_start_CMockStopIgnore(void)
{
  if(Mock.pcapping_protocol_start_IgnoreBool)
    Mock.pcapping_protocol_start_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_start_CallInstance);
  Mock.pcapping_protocol_start_IgnoreBool = (char)0;
}

void pcapping_protocol_start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_start_CALL_INSTANCE));
  CMOCK_pcapping_protocol_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_start_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_start_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_start_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pcapping_protocol_start_AddCallback(CMOCK_pcapping_protocol_start_CALLBACK Callback)
{
  Mock.pcapping_protocol_start_IgnoreBool = (char)0;
  Mock.pcapping_protocol_start_CallbackBool = (char)1;
  Mock.pcapping_protocol_start_CallbackFunctionPointer = Callback;
}

void pcapping_protocol_start_Stub(CMOCK_pcapping_protocol_start_CALLBACK Callback)
{
  Mock.pcapping_protocol_start_IgnoreBool = (char)0;
  Mock.pcapping_protocol_start_CallbackBool = (char)0;
  Mock.pcapping_protocol_start_CallbackFunctionPointer = Callback;
}

int pcapping_protocol_process_bind_request(fwk_id_t api_id, const void** api)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_pcapping_protocol_process_bind_request);
  cmock_call_instance = (CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pcapping_protocol_process_bind_request_CallInstance);
  Mock.pcapping_protocol_process_bind_request_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_process_bind_request_CallInstance);
  if (Mock.pcapping_protocol_process_bind_request_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.pcapping_protocol_process_bind_request_FinalReturn;
    Mock.pcapping_protocol_process_bind_request_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.pcapping_protocol_process_bind_request_CallbackBool &&
      Mock.pcapping_protocol_process_bind_request_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.pcapping_protocol_process_bind_request_CallbackFunctionPointer(api_id, api, Mock.pcapping_protocol_process_bind_request_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_api_id)
  {
    UNITY_SET_DETAILS(CMockString_pcapping_protocol_process_bind_request,CMockString_api_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_api_id), (void*)(&api_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_api)
  {
    UNITY_SET_DETAILS(CMockString_pcapping_protocol_process_bind_request,CMockString_api);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_api, api, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.pcapping_protocol_process_bind_request_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.pcapping_protocol_process_bind_request_CallbackFunctionPointer(api_id, api, Mock.pcapping_protocol_process_bind_request_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_api_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(api, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)api, (void*)cmock_call_instance->ReturnThruPtr_api_Val,
      cmock_call_instance->ReturnThruPtr_api_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pcapping_protocol_process_bind_request(CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance, fwk_id_t api_id, const void** api, int api_Depth);
void CMockExpectParameters_pcapping_protocol_process_bind_request(CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance, fwk_id_t api_id, const void** api, int api_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_api_id), (void*)(&api_id),
         sizeof(fwk_id_t[sizeof(api_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_api_id = 0;
  cmock_call_instance->Expected_api = api;
  cmock_call_instance->Expected_api_Depth = api_Depth;
  cmock_call_instance->IgnoreArg_api = 0;
  cmock_call_instance->ReturnThruPtr_api_Used = 0;
}

void pcapping_protocol_process_bind_request_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_bind_request_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_bind_request_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_bind_request_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.pcapping_protocol_process_bind_request_IgnoreBool = (char)1;
}

void pcapping_protocol_process_bind_request_CMockStopIgnore(void)
{
  if(Mock.pcapping_protocol_process_bind_request_IgnoreBool)
    Mock.pcapping_protocol_process_bind_request_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_process_bind_request_CallInstance);
  Mock.pcapping_protocol_process_bind_request_IgnoreBool = (char)0;
}

void pcapping_protocol_process_bind_request_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_bind_request_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_bind_request_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_bind_request_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void pcapping_protocol_process_bind_request_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t api_id, const void** api, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_bind_request_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_bind_request_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_bind_request_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_pcapping_protocol_process_bind_request(cmock_call_instance, api_id, api, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pcapping_protocol_process_bind_request_AddCallback(CMOCK_pcapping_protocol_process_bind_request_CALLBACK Callback)
{
  Mock.pcapping_protocol_process_bind_request_IgnoreBool = (char)0;
  Mock.pcapping_protocol_process_bind_request_CallbackBool = (char)1;
  Mock.pcapping_protocol_process_bind_request_CallbackFunctionPointer = Callback;
}

void pcapping_protocol_process_bind_request_Stub(CMOCK_pcapping_protocol_process_bind_request_CALLBACK Callback)
{
  Mock.pcapping_protocol_process_bind_request_IgnoreBool = (char)0;
  Mock.pcapping_protocol_process_bind_request_CallbackBool = (char)0;
  Mock.pcapping_protocol_process_bind_request_CallbackFunctionPointer = Callback;
}

void pcapping_protocol_process_bind_request_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t api_id, const void** api, int api_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_bind_request_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_bind_request_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_bind_request_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_pcapping_protocol_process_bind_request(cmock_call_instance, api_id, api, api_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pcapping_protocol_process_bind_request_CMockReturnMemThruPtr_api(UNITY_LINE_TYPE cmock_line, const void** api, size_t cmock_size)
{
  CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pcapping_protocol_process_bind_request_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_api_Used = 1;
  cmock_call_instance->ReturnThruPtr_api_Val = api;
  cmock_call_instance->ReturnThruPtr_api_Size = cmock_size;
}

void pcapping_protocol_process_bind_request_CMockIgnoreArg_api_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pcapping_protocol_process_bind_request_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_api_id = 1;
}

void pcapping_protocol_process_bind_request_CMockIgnoreArg_api(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_bind_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pcapping_protocol_process_bind_request_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_api = 1;
}

int pcapping_protocol_process_cap_pai_notify_event(const struct fwk_event* event)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_pcapping_protocol_process_cap_pai_notify_event);
  cmock_call_instance = (CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance);
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance);
  if (Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.pcapping_protocol_process_cap_pai_notify_event_FinalReturn;
    Mock.pcapping_protocol_process_cap_pai_notify_event_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackBool &&
      Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackFunctionPointer(event, Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_event)
  {
    UNITY_SET_DETAILS(CMockString_pcapping_protocol_process_cap_pai_notify_event,CMockString_event);
    if (cmock_call_instance->Expected_event == NULL)
      { UNITY_TEST_ASSERT_NULL(event, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_event), (void*)(event), sizeof(const struct fwk_event), cmock_call_instance->Expected_event_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackFunctionPointer(event, Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pcapping_protocol_process_cap_pai_notify_event(CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE* cmock_call_instance, const struct fwk_event* event, int event_Depth);
void CMockExpectParameters_pcapping_protocol_process_cap_pai_notify_event(CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE* cmock_call_instance, const struct fwk_event* event, int event_Depth)
{
  cmock_call_instance->Expected_event = event;
  cmock_call_instance->Expected_event_Depth = event_Depth;
  cmock_call_instance->IgnoreArg_event = 0;
}

void pcapping_protocol_process_cap_pai_notify_event_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool = (char)1;
}

void pcapping_protocol_process_cap_pai_notify_event_CMockStopIgnore(void)
{
  if(Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool)
    Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance);
  Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool = (char)0;
}

void pcapping_protocol_process_cap_pai_notify_event_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void pcapping_protocol_process_cap_pai_notify_event_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_event* event, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_pcapping_protocol_process_cap_pai_notify_event(cmock_call_instance, event, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pcapping_protocol_process_cap_pai_notify_event_AddCallback(CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALLBACK Callback)
{
  Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool = (char)0;
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackBool = (char)1;
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackFunctionPointer = Callback;
}

void pcapping_protocol_process_cap_pai_notify_event_Stub(CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALLBACK Callback)
{
  Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool = (char)0;
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackBool = (char)0;
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallbackFunctionPointer = Callback;
}

void pcapping_protocol_process_cap_pai_notify_event_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_event* event, int event_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_cap_pai_notify_event_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_pcapping_protocol_process_cap_pai_notify_event(cmock_call_instance, event, event_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pcapping_protocol_process_cap_pai_notify_event_CMockIgnoreArg_event(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_cap_pai_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pcapping_protocol_process_cap_pai_notify_event_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_event = 1;
}

int pcapping_protocol_process_measurements_notify_event(const struct fwk_event* event)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_pcapping_protocol_process_measurements_notify_event);
  cmock_call_instance = (CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pcapping_protocol_process_measurements_notify_event_CallInstance);
  Mock.pcapping_protocol_process_measurements_notify_event_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_process_measurements_notify_event_CallInstance);
  if (Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.pcapping_protocol_process_measurements_notify_event_FinalReturn;
    Mock.pcapping_protocol_process_measurements_notify_event_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.pcapping_protocol_process_measurements_notify_event_CallbackBool &&
      Mock.pcapping_protocol_process_measurements_notify_event_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.pcapping_protocol_process_measurements_notify_event_CallbackFunctionPointer(event, Mock.pcapping_protocol_process_measurements_notify_event_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_event)
  {
    UNITY_SET_DETAILS(CMockString_pcapping_protocol_process_measurements_notify_event,CMockString_event);
    if (cmock_call_instance->Expected_event == NULL)
      { UNITY_TEST_ASSERT_NULL(event, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_event), (void*)(event), sizeof(const struct fwk_event), cmock_call_instance->Expected_event_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.pcapping_protocol_process_measurements_notify_event_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.pcapping_protocol_process_measurements_notify_event_CallbackFunctionPointer(event, Mock.pcapping_protocol_process_measurements_notify_event_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pcapping_protocol_process_measurements_notify_event(CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE* cmock_call_instance, const struct fwk_event* event, int event_Depth);
void CMockExpectParameters_pcapping_protocol_process_measurements_notify_event(CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE* cmock_call_instance, const struct fwk_event* event, int event_Depth)
{
  cmock_call_instance->Expected_event = event;
  cmock_call_instance->Expected_event_Depth = event_Depth;
  cmock_call_instance->IgnoreArg_event = 0;
}

void pcapping_protocol_process_measurements_notify_event_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_measurements_notify_event_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_measurements_notify_event_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool = (char)1;
}

void pcapping_protocol_process_measurements_notify_event_CMockStopIgnore(void)
{
  if(Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool)
    Mock.pcapping_protocol_process_measurements_notify_event_CallInstance = CMock_Guts_MemNext(Mock.pcapping_protocol_process_measurements_notify_event_CallInstance);
  Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool = (char)0;
}

void pcapping_protocol_process_measurements_notify_event_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_measurements_notify_event_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_measurements_notify_event_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void pcapping_protocol_process_measurements_notify_event_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_event* event, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_measurements_notify_event_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_measurements_notify_event_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_pcapping_protocol_process_measurements_notify_event(cmock_call_instance, event, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pcapping_protocol_process_measurements_notify_event_AddCallback(CMOCK_pcapping_protocol_process_measurements_notify_event_CALLBACK Callback)
{
  Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool = (char)0;
  Mock.pcapping_protocol_process_measurements_notify_event_CallbackBool = (char)1;
  Mock.pcapping_protocol_process_measurements_notify_event_CallbackFunctionPointer = Callback;
}

void pcapping_protocol_process_measurements_notify_event_Stub(CMOCK_pcapping_protocol_process_measurements_notify_event_CALLBACK Callback)
{
  Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool = (char)0;
  Mock.pcapping_protocol_process_measurements_notify_event_CallbackBool = (char)0;
  Mock.pcapping_protocol_process_measurements_notify_event_CallbackFunctionPointer = Callback;
}

void pcapping_protocol_process_measurements_notify_event_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_event* event, int event_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE));
  CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pcapping_protocol_process_measurements_notify_event_CallInstance = CMock_Guts_MemChain(Mock.pcapping_protocol_process_measurements_notify_event_CallInstance, cmock_guts_index);
  Mock.pcapping_protocol_process_measurements_notify_event_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_pcapping_protocol_process_measurements_notify_event(cmock_call_instance, event, event_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pcapping_protocol_process_measurements_notify_event_CMockIgnoreArg_event(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_pcapping_protocol_process_measurements_notify_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pcapping_protocol_process_measurements_notify_event_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_event = 1;
}

